This example notebooks shows the local execution of Comp2Prot and of the singular databases. Note: Download the updated databases from the Dropbox link in the data folder.

In [1]:
#General packages
import pandas as pd
from tqdm import tqdm
import os
from cpiextract import Comp2Prot
import time
import cProfile

In [8]:
# Root data path
data_path = 'data/Databases/'

# Load in Datasets

Datasets which require local copies

In [4]:
#Downloaded from BindingDB on 12/8/2025
file_path=os.path.join(data_path, 'BindingDB_Dec2025.csv')
BDB_data=pd.read_csv(file_path,sep=',',low_memory=False,index_col=0)

#Downloaded from STITCH on 2/22/2023 unchanged on 12/8/2025
file_path=os.path.join(data_path, 'STITCH.csv')
sttch_data=pd.read_csv(file_path,sep=',',low_memory=False,index_col=0)

#Downloaded from CTD 12/8/2025
file_path=os.path.join(data_path, 'CTD_Dec2025.csv')
CTD_data=pd.read_csv(file_path,sep=',',low_memory=False,index_col=0)

#Downloaded from DTC on 2/24/2023 unchanged on 12/8/2025
file_path=os.path.join(data_path, 'DTC_Dec2025.csv')
DTC_data=pd.read_csv(file_path,sep=',',low_memory=False,index_col=0)

#Downloaded from DrugBank on 12/8/2025
file_path=os.path.join(data_path, 'DB_Dec2025.csv')
DB_data=pd.read_csv(file_path, sep=',',low_memory=False,index_col=0)

#Downloaded from DrugCentral on 2/25/2024 unchanged on 12/8/2025
file_path=os.path.join(data_path, 'DrugCentral_Dec2025.csv')
DC_data=pd.read_csv(file_path, sep=',',low_memory=False,index_col=0)

Datasets with APIs or can be run locally for faster speeds

In [16]:
#Downloaded from ChEMBL on 12/8/2025
file_path=os.path.join(data_path, 'ChEMBL_Dec2025.csv')
chembl_data=pd.read_csv(file_path,sep=',',low_memory=False,index_col=0)

#Downloaded from OTP on 2/2/2026
file_path=os.path.join(data_path, 'OTP_Dec2025.csv')
OTP_data=pd.read_csv(file_path, sep=',',low_memory=False,index_col=0)

If you have the resources to run a local copy of PubChem, Otherwise do not run.

In [31]:
#Local PubChem will improve speed
file_path=os.path.join(data_path, 'pubchem/pubchem.duckdb')
pubchem_files = {'db_file': file_path}

Build database dictionary

In [17]:
#Suppress OTP or ChEMBL if local copies are not available
dbs = {
    'chembl': chembl_data,
    'bdb': BDB_data,
    'stitch': sttch_data,
    'ctd': CTD_data,
    'dtc': DTC_data,
    'db': DB_data,
    'dc': DC_data,
    'otp': OTP_data
}

## Load in Compound List

DrugBank compounds

In [19]:
#chem_dat=pd.read_csv('data/input/db_compounds.csv')
chem_dat=pd.read_csv(data_path+'db_compounds.csv')
output_path = 'data/output/C2P'

FooDB compounds

In [ ]:
#chem_dat=pd.read_csv('data/input/foodb_compounds.csv')
chem_dat=pd.read_csv(data_path+'foodb_compounds.csv')
output_path = 'data/output/foodb'

## Run Comp2Prot on Compound List

In [33]:
if 'pubchem_files' in locals():
    C2P = Comp2Prot('local', dbs=dbs, pubchem_files=pubchem_files)
    print('Using local copy of PubChem')
else:
    C2P = Comp2Prot('local', dbs=dbs) 
    print('Using PubChem API')

Using local copy of PubChem

In [15]:
times = {}

In [34]:
c2p_dat=pd.DataFrame()
c2p_fail=pd.DataFrame()
states = pd.DataFrame()

r=0
for h in tqdm(range(0,10)):

    try:
        inputid=chem_dat['inchikey'].iloc[h]
    except:
        continue
    start = time.time()

    try:
        #merge_steroisomers if True will search for all stereochemistries
        [comp_dat,state]=C2P.comp_interactions(inputid,merge_stereoisomers=False,verbose=False)
        end = time.time()
        times[h] = end-start
        states = pd.concat([states, state])
        c2p_dat=pd.concat([c2p_dat,comp_dat])
        print(f'{h} done')
    except:
        print(f'{h} failed')
        c2p_fail.loc[r,"failed_id"]=inputid #Collects failed inputids
        r=r+1

    # Saves a file after a certain number of loops for insurance
    check=h/50 #automatically saves progress when on loop number set here
    if (check-int(check)==0)==True:
        filename=os.path.join(output_path, '_iter_'+str(h)+'.csv')
        c2p_dat.to_csv(filename,sep=',',index=False)

# Save completed dataframe to file
filename=os.path.join(output_path, '.csv')
c2p_dat.to_csv(filename,sep=',',index=False)

  0%|          | 0/10 [00:00<?, ?it/s]/home/m.sebekington/cpiextract/servers/BiomartServer.py:51: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  targets = pd.concat([targets, sub_targets])
 10%|█         | 1/10 [00:43<06:27, 43.03s/it]

0 done

/home/m.sebekington/cpiextract/servers/BiomartServer.py:51: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  targets = pd.concat([targets, sub_targets])
 20%|██        | 2/10 [01:36<06:31, 48.89s/it]

1 done

/home/m.sebekington/cpiextract/servers/BiomartServer.py:51: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  targets = pd.concat([targets, sub_targets])
 30%|███       | 3/10 [02:09<04:52, 41.81s/it]

2 done

/home/m.sebekington/cpiextract/servers/BiomartServer.py:47: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  targets = pd.concat([targets, sub_targets])
 40%|████      | 4/10 [03:06<04:46, 47.81s/it]

3 done

 50%|█████     | 5/10 [03:31<03:18, 39.60s/it]

4 done

 60%|██████    | 6/10 [03:46<02:04, 31.10s/it]

5 done

 70%|███████   | 7/10 [04:42<01:58, 39.52s/it]

6 done

/home/m.sebekington/cpiextract/servers/BiomartServer.py:47: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  targets = pd.concat([targets, sub_targets])
 80%|████████  | 8/10 [06:09<01:49, 54.58s/it]

7 done

 90%|█████████ | 9/10 [07:31<01:03, 63.17s/it]

8 done

/home/m.sebekington/cpiextract/servers/BiomartServer.py:51: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  targets = pd.concat([targets, sub_targets])
100%|██████████| 10/10 [08:26<00:00, 50.65s/it]

9 done

In [35]:
c2p_dat

,input_id,pc_inchi,pc_inchikey,pc_firstblock,pc_iso_smiles,pc_iupac_name,pc_cid,db_inchikey,entrez,gene_type,...,src_count,pubchem,chembl,bindingdb,stitch,ctd,dtc,otp,drugcentral,drugbank
0,ISWSIDIOOBJBQZ-UHFFFAOYSA-N,"InChI=1S/C6H6O/c7-6-4-2-1-3-5-6/h1-5,7H",ISWSIDIOOBJBQZ-UHFFFAOYSA-N,ISWSIDIOOBJBQZ,None,phenol,996,ISWSIDIOOBJBQZ-UHFFFAOYSA-N,760,protein_coding,...,5,1,1,1,0,0,1,0,0,1
1,ISWSIDIOOBJBQZ-UHFFFAOYSA-N,"InChI=1S/C6H6O/c7-6-4-2-1-3-5-6/h1-5,7H",ISWSIDIOOBJBQZ-UHFFFAOYSA-N,ISWSIDIOOBJBQZ,None,phenol,996,ISWSIDIOOBJBQZ-UHFFFAOYSA-N,761,protein_coding,...,4,1,1,1,0,0,1,0,0,0
2,ISWSIDIOOBJBQZ-UHFFFAOYSA-N,"InChI=1S/C6H6O/c7-6-4-2-1-3-5-6/h1-5,7H",ISWSIDIOOBJBQZ-UHFFFAOYSA-N,ISWSIDIOOBJBQZ,None,phenol,996,ISWSIDIOOBJBQZ-UHFFFAOYSA-N,762,protein_coding,...,5,1,1,1,0,0,1,0,0,1
3,ISWSIDIOOBJBQZ-UHFFFAOYSA-N,"InChI=1S/C6H6O/c7-6-4-2-1-3-5-6/h1-5,7H",ISWSIDIOOBJBQZ-UHFFFAOYSA-N,ISWSIDIOOBJBQZ,None,phenol,996,ISWSIDIOOBJBQZ-UHFFFAOYSA-N,768,protein_coding,...,5,1,1,1,0,0,1,0,0,1
4,ISWSIDIOOBJBQZ-UHFFFAOYSA-N,"InChI=1S/C6H6O/c7-6-4-2-1-3-5-6/h1-5,7H",ISWSIDIOOBJBQZ-UHFFFAOYSA-N,ISWSIDIOOBJBQZ,None,phenol,996,ISWSIDIOOBJBQZ-UHFFFAOYSA-N,771,protein_coding,...,5,1,1,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,XUJNEKJLAYXESH-REOHCLBHSA-N,"InChI=1S/C3H7NO2S/c4-2(1-7)3(5)6/h2,7H,1,4H2,(...",XUJNEKJLAYXESH-REOHCLBHSA-N,XUJNEKJLAYXESH,None,(2R)-2-amino-3-sulfanylpropanoic acid,5862,XUJNEKJLAYXESH-REOHCLBHSA-N,1491,protein_coding,...,1,0,0,0,0,0,0,0,0,1
88,XUJNEKJLAYXESH-REOHCLBHSA-N,"InChI=1S/C3H7NO2S/c4-2(1-7)3(5)6/h2,7H,1,4H2,(...",XUJNEKJLAYXESH-REOHCLBHSA-N,XUJNEKJLAYXESH,None,(2R)-2-amino-3-sulfanylpropanoic acid,5862,XUJNEKJLAYXESH-REOHCLBHSA-N,4255,protein_coding,...,1,0,0,0,0,0,0,0,0,1
89,XUJNEKJLAYXESH-REOHCLBHSA-N,"InChI=1S/C3H7NO2S/c4-2(1-7)3(5)6/h2,7H,1,4H2,(...",XUJNEKJLAYXESH-REOHCLBHSA-N,XUJNEKJLAYXESH,None,(2R)-2-amino-3-sulfanylpropanoic acid,5862,XUJNEKJLAYXESH-REOHCLBHSA-N,2937,protein_coding,...,1,0,0,0,0,0,0,0,0,1
90,XUJNEKJLAYXESH-REOHCLBHSA-N,"InChI=1S/C3H7NO2S/c4-2(1-7)3(5)6/h2,7H,1,4H2,(...",XUJNEKJLAYXESH-REOHCLBHSA-N,XUJNEKJLAYXESH,None,(2R)-2-amino-3-sulfanylpropanoic acid,5862,XUJNEKJLAYXESH-REOHCLBHSA-N,51380,protein_coding,...,1,0,0,0,0,0,0,0,0,1
91,XUJNEKJLAYXESH-REOHCLBHSA-N,"InChI=1S/C3H7NO2S/c4-2(1-7)3(5)6/h2,7H,1,4H2,(...",XUJNEKJLAYXESH-REOHCLBHSA-N,XUJNEKJLAYXESH,None,(2R)-2-amino-3-sulfanylpropanoic acid,5862,XUJNEKJLAYXESH-REOHCLBHSA-N,117247,protein_coding,...,1,0,0,0,0,0,0,0,0,1

In [36]:
states

,comp,pc,chembl,bdb,stitch,ctd,dtc,otp,dc,db
0,ISWSIDIOOBJBQZ-UHFFFAOYSA-N,completed (local),completed,completed,completed,No interaction data,completed,No ChEMBL ids found in local OTP,Filter reduced interactions to 0,completed
0,CZMRCDWAGMRECN-UGDNZRGBSA-N,completed (local),Filter reduced interactions to 0,completed,completed,completed,completed,No ChEMBL ids found in local OTP,No interaction data,completed
0,JVTAAEKCZFNVCJ-UHFFFAOYSA-N,completed (local),Filter reduced interactions to 0,No interaction data,completed,No interaction data,Filter reduced interactions to 0,No ChEMBL ids found in local OTP,No interaction data,completed
0,ZMXDDKWLCZADIW-UHFFFAOYSA-N,completed (local),Filter reduced interactions to 0,No interaction data,completed,completed,Filter reduced interactions to 0,No ChEMBL ids found in local OTP,No interaction data,completed
0,PNDPGZBMCMUPRI-UHFFFAOYSA-N,completed (local),No interaction data,No interaction data,Filter reduced interactions to 0,Filter reduced interactions to 0,Filter reduced interactions to 0,No ChEMBL ids found in local OTP,No interaction data,completed
0,IJGRMHOSHXDMSA-UHFFFAOYSA-N,No interaction data in local files,No interaction data,No interaction data,Filter reduced interactions to 0,completed,No interaction data,No ChEMBL ids found in local OTP,No interaction data,No interaction data
0,WPYMKLBDIGXBTP-UHFFFAOYSA-N,completed (local),completed,completed,No interaction data,No interaction data,completed,No ChEMBL ids found in local OTP,Filter reduced interactions to 0,completed
0,KDYFGRWQOYBRFD-UHFFFAOYSA-N,completed (local),completed,completed,completed,No interaction data,completed,No ChEMBL ids found in local OTP,completed,completed
0,RYYVLZVUVIJVGH-UHFFFAOYSA-N,completed (local),completed,completed,completed,completed,completed,completed,completed,completed
0,XUJNEKJLAYXESH-REOHCLBHSA-N,completed (local),completed,completed,completed,No interaction data,completed,No ChEMBL ids found in local OTP,Filter reduced interactions to 0,completed

# Run Comp2Prot on Single Compound

## Comp2Prot with all Databases

### Test time required

In [38]:
inputid='SUVMJBTUFCVSAD-UHFFFAOYSA-N'
#inputid=5350

In [39]:
cProfile.run('C2P.comp_interactions(inputid,merge_stereoisomers=False,verbose=False)')

         645690 function calls (639182 primitive calls) in 35.745 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      177    0.000    0.000    0.001    0.000 <frozen _collections_abc>:804(get)
       86    0.000    0.000    0.000    0.000 <frozen _collections_abc>:811(__contains__)
       36    0.000    0.000    0.000    0.000 <frozen _collections_abc>:819(keys)
       64    0.000    0.000    0.000    0.000 <frozen _collections_abc>:823(items)
      100    0.000    0.000    0.000    0.000 <frozen _collections_abc>:845(__init__)
       16    0.000    0.000    0.000    0.000 <frozen _collections_abc>:848(__len__)
     4572    0.001    0.000    0.007    0.000 <frozen _collections_abc>:868(__iter__)
      322    0.000    0.000    0.001    0.000 <frozen _collections_abc>:892(__iter__)
      142    0.001    0.000    0.002    0.000 <frozen _collections_abc>:974(update)
     1364    0.001    0.000    0.002    0.000 <frozen abc>:117(__instancecheck__)
        7    0.000    0.000    0.000    0.000 <frozen abc>:121(__subclasscheck__)
        5    0.000    0.000    0.000    0.000 <frozen codecs>:186(__init__)
        5    0.000    0.000    0.000    0.000 <frozen codecs>:260(__init__)
      162    0.000    0.000    0.000    0.000 <frozen codecs>:276(reset)
       34    0.000    0.000    0.002    0.000 <frozen genericpath>:16(exists)
        1    0.000    0.000    0.000    0.000 <frozen genericpath>:39(isdir)
       92    0.000    0.000    0.000    0.000 <frozen importlib._bootstrap>:1390(_handle_fromlist)
      289    0.001    0.000    0.001    0.000 <frozen os>:709(__getitem__)
     4572    0.002    0.000    0.005    0.000 <frozen os>:732(__iter__)
      289    0.000    0.000    0.000    0.000 <frozen os>:791(encode)
     4708    0.002    0.000    0.003    0.000 <frozen os>:795(decode)
       33    0.000    0.000    0.001    0.000 <frozen posixpath>:256(expanduser)
       32    0.000    0.000    0.000    0.000 <frozen posixpath>:41(_get_sep)
      211    0.000    0.000    0.000    0.000 <string>:1(<lambda>)
        6    0.000    0.000    0.000    0.000 <string>:2(__init__)
        1    0.000    0.000    6.324    6.324 BindingDB.py:105(interactions)
        1    0.000    0.000    0.006    0.006 BindingDB.py:21(_filter_database)
        1    0.000    0.000    0.022    0.022 BindingDB.py:51(_compute_pchembl)
       20    0.000    0.000    0.000    0.000 BindingDB.py:75(<lambda>)
        5    0.000    0.000   30.174    6.035 BiomartServer.py:22(search)
        5    0.000    0.000   30.191    6.038 BiomartServer.py:39(subset_search)
        1    0.000    0.000    0.095    0.095 CTD.py:28(interactions)
        1    0.000    0.000    0.005    0.005 ChEMBL.py:37(_filter_database)
       29    0.000    0.000    0.000    0.000 ChEMBL.py:53(<lambda>)
        1    0.000    0.000    6.522    6.522 ChEMBL.py:60(interactions)
        6    0.000    0.000    0.002    0.000 Comp2Prot.py:104(<lambda>)
        1    0.001    0.001    0.022    0.022 Comp2Prot.py:121(_postprocess_databases)
        1    0.000    0.000    0.000    0.000 Comp2Prot.py:9(_update_args)
        1    0.000    0.000    0.004    0.004 DTC.py:26(_filter_database)
        1    0.000    0.000    0.015    0.015 DTC.py:312(_standard_converter)
        1    0.000    0.000    0.020    0.020 DTC.py:52(_standardize_database)
        1    0.000    0.000    6.396    6.396 DTC.py:80(interactions)
        1    0.000    0.000    0.010    0.010 DrugBank.py:22(interactions)
        1    0.000    0.000    0.005    0.005 DrugCentral.py:46(interactions)
    16105    0.002    0.000    0.002    0.000 ElementPath.py:165(select)
1300/1170    0.000    0.000    0.000    0.000 ElementPath.py:173(select)
       80    0.000    0.000    0.000    0.000 ElementPath.py:179(select)
       65    0.004    0.000    0.009    0.000 ElementPath.py:260(select)
       40    0.000    0.000    0.000    0.000 ElementPath.py:352(__init__)
       40    0.000    0.000    0.000    0.000 ElementPath.py:360(iterfind)
       40    0.000    0.000    0.009    0.000 ElementPath.py:410(findall)
       74    0.000    0.000    0.000    0.000 ElementTree.py:1024(_escape_attrib)
        5    0.000    0.000    0.002    0.000 ElementTree.py:1067(tostring)
        5    0.023    0.005    0.301    0.060 ElementTree.py:1322(XML)
        5    0.000    0.000    0.000    0.000 ElementTree.py:525(__init__)
        5    0.000    0.000    0.002    0.000 ElementTree.py:679(write)
       10    0.000    0.000    0.000    0.000 ElementTree.py:739(_get_writer)
        5    0.000    0.000    0.000    0.000 ElementTree.py:789(_namespaces)
       65    0.000    0.000    0.000    0.000 ElementTree.py:800(add_qname)
     39/5    0.000    0.000    0.001    0.000 ElementTree.py:850(_serialize_xml)
        8    0.000    0.000    2.049    0.256 LocalManager.py:6(retrieve_raw_data)
        1    0.000    0.000    0.004    0.004 OTP.py:51(interactions)
        4    0.000    0.000    0.003    0.001 Pipeline.py:117(_aggregate_pchembl)
        1    0.000    0.000    0.010    0.010 PubChem.py:42(_filter_database)
        1    0.163    0.163    2.310    2.310 PubChem.py:471(_retrieve_from_local)
        1    0.000    0.000    0.000    0.000 PubChemServer.py:13(get_columns)
        1    0.000    0.000    0.160    0.160 PubChemServer.py:16(get_compounds)
        1    0.000    0.000    0.000    0.000 PubChemServer.py:63(get_inchikey_first_block)
        1    0.000    0.000    7.583    7.583 Stitch.py:23(interactions)
        1    0.000    0.000    0.678    0.678 Stitch.py:232(_extract_ids)
       41    0.000    0.000    0.000    0.000 __init__.py:1517(debug)
        5    0.000    0.000    0.000    0.000 __init__.py:179(sub)
       41    0.000    0.000    0.000    0.000 __init__.py:1790(isEnabledFor)
       61    0.000    0.000    0.000    0.000 __init__.py:226(compile)
        2    0.000    0.000    0.000    0.000 __init__.py:255(escape)
       66    0.000    0.000    0.000    0.000 __init__.py:280(_compile)
        4    0.000    0.000    0.001    0.000 __init__.py:299(loads)
     3658    0.001    0.000    0.001    0.000 __init__.py:34(using_copy_on_write)
     1488    0.000    0.000    0.000    0.000 __init__.py:42(warn_copy_on_write)
      342    0.000    0.000    0.001    0.000 __init__.py:535(_check_cacher)
      447    0.000    0.000    0.000    0.000 __init__.py:55(using_string_dtype)
       54    0.000    0.000    0.001    0.000 _asarray.py:27(require)
       16    0.000    0.000    0.001    0.000 _collections.py:141(__init__)
      225    0.000    0.000    0.000    0.000 _collections.py:156(__getitem__)
      177    0.000    0.000    0.000    0.000 _collections.py:187(__iter__)
      161    0.000    0.000    0.000    0.000 _collections.py:215(add)
       16    0.000    0.000    0.001    0.000 _collections.py:231(extend)
       48    0.000    0.000    0.000    0.000 _collections.py:47(__init__)
       16    0.000    0.000    0.000    0.000 _collections.py:54(__getitem__)
       16    0.000    0.000    0.000    0.000 _collections.py:61(__setitem__)
       48    0.000    0.000    0.000    0.000 _collections.py:92(clear)
        5    0.000    0.000    0.000    0.000 _decorators.py:325(wrapper)
      342    0.000    0.000    0.000    0.000 _dtype.py:24(_kind_name)
      342    0.000    0.000    0.001    0.000 _dtype.py:330(_name_includes_bit_suffix)
      342    0.001    0.000    0.002    0.000 _dtype.py:346(_name_get)
       80    0.000    0.000    0.000    0.000 _internal_utils.py:25(to_native_string)
       16    0.000    0.000    0.000    0.000 _internal_utils.py:38(unicode_is_ascii)
        4    0.000    0.000    0.000    0.000 _methods.py:101(_mean)
        4    0.000    0.000    0.000    0.000 _methods.py:135(_var)
        4    0.000    0.000    0.000    0.000 _methods.py:204(_std)
      129    0.000    0.000    0.001    0.000 _methods.py:39(_amax)
       37    0.000    0.000    0.000    0.000 _methods.py:43(_amin)
       15    0.000    0.000    0.000    0.000 _methods.py:47(_sum)
      364    0.000    0.000    0.002    0.000 _methods.py:55(_any)
       90    0.000    0.000    0.002    0.000 _methods.py:61(_all)
        8    0.000    0.000    0.000    0.000 _methods.py:67(_count_reduce_items)
        8    0.000    0.000    0.001    0.000 _monitor.py:47(get_instances)
      281    0.000    0.000    0.001    0.000 _policybase.py:281(_sanitize_header)
      233    0.001    0.000    0.001    0.000 _policybase.py:293(header_source_parse)
      281    0.000    0.000    0.001    0.000 _policybase.py:311(header_fetch_parse)
       12    0.000    0.000    0.000    0.000 _ufunc_config.py:132(geterr)
       12    0.000    0.000    0.000    0.000 _ufunc_config.py:33(seterr)
        6    0.000    0.000    0.000    0.000 _ufunc_config.py:426(__init__)
        6    0.000    0.000    0.000    0.000 _ufunc_config.py:430(__enter__)
        6    0.000    0.000    0.000    0.000 _ufunc_config.py:435(__exit__)
        8    0.000    0.000    0.000    0.000 _ufunc_config.py:452(_no_nep50_warning)
       16    0.000    0.000    0.000    0.000 _validators.py:128(_check_for_invalid_keys)
       16    0.000    0.000    0.000    0.000 _validators.py:141(validate_kwargs)
        1    0.000    0.000    0.000    0.000 _validators.py:168(validate_args_and_kwargs)
      163    0.000    0.000    0.000    0.000 _validators.py:226(validate_bool_kwarg)
        1    0.000    0.000    0.000    0.000 _validators.py:29(_check_arg_length)
       70    0.000    0.000    0.000    0.000 _validators.py:450(check_dtype_backend)
       16    0.000    0.000    0.000    0.000 _validators.py:49(_check_for_default_values)
        8    0.000    0.000    0.000    0.000 _weakrefset.py:120(update)
       16    0.000    0.000    0.000    0.000 _weakrefset.py:17(__init__)
       16    0.000    0.000    0.000    0.000 _weakrefset.py:21(__enter__)
       16    0.000    0.000    0.000    0.000 _weakrefset.py:27(__exit__)
        8    0.000    0.000    0.000    0.000 _weakrefset.py:37(__init__)
       16    0.000    0.000    0.000    0.000 _weakrefset.py:53(_commit_removals)
       16    0.000    0.000    0.000    0.000 _weakrefset.py:63(__iter__)
        8    0.000    0.000    0.000    0.000 _weakrefset.py:95(copy)
        3    0.000    0.000    0.001    0.000 accessor.py:132(wrapper)
        2    0.000    0.000    0.001    0.000 accessor.py:1432(replace)
        4    0.000    0.000    0.000    0.000 accessor.py:191(__init__)
        4    0.000    0.000    0.000    0.000 accessor.py:210(_validate)
        4    0.000    0.000    0.000    0.000 accessor.py:220(__get__)
        1    0.000    0.000    0.000    0.000 accessor.py:251(__getitem__)
        4    0.000    0.000    0.001    0.000 accessor.py:258(_wrap_result)
        1    0.000    0.000    0.000    0.000 accessor.py:3219(lower)
       32    0.000    0.000    0.000    0.000 adapters.py:116(__init__)
       32    0.000    0.000    0.001    0.000 adapters.py:178(__init__)
       32    0.000    0.000    0.000    0.000 adapters.py:216(init_poolmanager)
       16    0.000    0.000    0.001    0.000 adapters.py:242(proxy_manager_for)
       16    0.000    0.000    0.001    0.000 adapters.py:280(cert_verify)
       16    0.000    0.000    0.003    0.000 adapters.py:336(build_response)
       16    0.000    0.000    0.000    0.000 adapters.py:373(build_connection_pool_key_attributes)
       16    0.000    0.000    0.007    0.000 adapters.py:423(get_connection_with_tls_context)
       32    0.000    0.000    0.001    0.000 adapters.py:513(close)
       16    0.000    0.000    0.001    0.000 adapters.py:523(request_url)
       16    0.000    0.000    0.000    0.000 adapters.py:555(add_headers)
       16    0.000    0.000    0.000    0.000 adapters.py:569(proxy_headers)
       16    0.000    0.000    2.083    0.130 adapters.py:590(send)
       16    0.000    0.000    0.000    0.000 adapters.py:76(_urllib3_request_context)
       87    0.000    0.000    0.001    0.000 algorithms.py:106(_ensure_data)
       52    0.000    0.000    0.001    0.000 algorithms.py:1131(take)
       13    0.000    0.000    0.001    0.000 algorithms.py:1667(map_array)
      127    0.000    0.000    0.000    0.000 algorithms.py:184(_reconstruct_data)
      153    0.001    0.000    0.001    0.000 algorithms.py:217(_ensure_arraylike)
       87    0.000    0.000    0.002    0.000 algorithms.py:262(_get_hashtable_algo)
       87    0.000    0.000    0.001    0.000 algorithms.py:280(_check_object_for_strings)
       47    0.000    0.000    0.002    0.000 algorithms.py:307(unique)
       47    0.001    0.000    0.002    0.000 algorithms.py:427(unique_with_mask)
       33    0.002    0.000    0.004    0.000 algorithms.py:457(isin)
       40    0.001    0.000    0.002    0.000 algorithms.py:548(factorize_array)
       40    0.000    0.000    0.002    0.000 algorithms.py:610(factorize)
        1    0.000    0.000    0.672    0.672 api.py:103(post)
       12    0.000    0.000    0.000    0.000 api.py:106(_get_distinct_objs)
       12    0.000    0.000    0.002    0.000 api.py:120(_get_combined_index)
       16    0.000    0.000    2.111    0.132 api.py:14(request)
        8    0.000    0.000    0.001    0.000 api.py:202(union_indexes)
        8    0.000    0.000    0.000    0.000 api.py:265(_find_common_index_dtype)
       19    0.000    0.000    0.001    0.000 api.py:318(<genexpr>)
        8    0.000    0.000    0.000    0.000 api.py:330(_sanitize_and_check)
       77    0.000    0.000    0.000    0.000 api.py:386(default_index)
       15    0.000    0.000    1.439    0.096 api.py:62(get)
       12    0.000    0.000    0.002    0.000 api.py:72(get_objs_combined_axis)
        3    0.000    0.000    0.004    0.001 apply.py:1061(apply_standard)
        3    0.000    0.000    0.003    0.001 apply.py:1070(apply_series_generator)
        3    0.000    0.000    0.001    0.000 apply.py:1102(wrap_results)
        3    0.000    0.000    0.000    0.000 apply.py:1137(series_generator)
       17    0.000    0.000    0.001    0.000 apply.py:1139(<genexpr>)
        3    0.000    0.000    0.000    0.000 apply.py:1185(result_index)
        4    0.000    0.000    0.000    0.000 apply.py:1189(result_columns)
        2    0.000    0.000    0.001    0.000 apply.py:1193(wrap_results_for_axis)
        2    0.000    0.000    0.000    0.000 apply.py:1204(<genexpr>)
        8    0.000    0.000    0.000    0.000 apply.py:121(__init__)
        5    0.000    0.000    0.000    0.000 apply.py:1372(__init__)
        5    0.000    0.000    0.001    0.000 apply.py:1404(apply)
        5    0.000    0.000    0.001    0.000 apply.py:1477(apply_standard)
       40    0.000    0.000    0.000    0.000 apply.py:1490(curried)
        3    0.000    0.000    0.000    0.000 apply.py:1638(reconstruct_func)
        4    0.000    0.000    0.000    0.000 apply.py:717(index)
        3    0.000    0.000    0.000    0.000 apply.py:773(__init__)
        3    0.000    0.000    0.000    0.000 apply.py:82(frame_apply)
        4    0.000    0.000    0.000    0.000 apply.py:852(res_columns)
        9    0.000    0.000    0.000    0.000 apply.py:856(columns)
        3    0.000    0.000    0.004    0.001 apply.py:864(apply)
       44    0.096    0.002    0.096    0.002 array_ops.py:113(comp_method_OBJECT_ARRAY)
       12    0.000    0.000    0.000    0.000 array_ops.py:189(_na_arithmetic_op)
        2    0.000    0.000    0.000    0.000 array_ops.py:240(arithmetic_op)
       55    0.000    0.000    1.206    0.022 array_ops.py:288(comparison_op)
       20    0.000    0.000    0.000    0.000 array_ops.py:352(na_logical_op)
       20    0.000    0.000    0.000    0.000 array_ops.py:393(logical_op)
       40    0.000    0.000    0.000    0.000 array_ops.py:410(fill_bool)
        2    0.000    0.000    0.000    0.000 array_ops.py:507(maybe_prepare_scalar_for_op)
        2    0.000    0.000    0.000    0.000 array_ops.py:594(_bool_arith_check)
        2    0.000    0.000    0.000    0.000 arraylike.py:208(__truediv__)
        2    0.000    0.000    0.000    0.000 arraylike.py:253(array_ufunc)
        4    0.000    0.000    0.000    0.000 arraylike.py:300(<genexpr>)
        2    0.000    0.000    0.000    0.000 arraylike.py:338(reconstruct)
        2    0.000    0.000    0.000    0.000 arraylike.py:345(_reconstruct)
       44    0.000    0.000    2.034    0.046 arraylike.py:38(__eq__)
        4    0.000    0.000    0.000    0.000 arraylike.py:398(<genexpr>)
        2    0.000    0.000    0.000    0.000 arraylike.py:418(_standardize_out_kwarg)
        2    0.000    0.000    0.000    0.000 arraylike.py:42(__ne__)
        2    0.000    0.000    0.000    0.000 arraylike.py:46(__lt__)
        7    0.000    0.000    0.001    0.000 arraylike.py:54(__gt__)
       18    0.000    0.000    0.002    0.000 arraylike.py:68(__and__)
        2    0.000    0.000    0.000    0.000 arraylike.py:76(__or__)
       48    0.000    0.000    0.001    0.000 astype.py:157(astype_array)
       36    0.000    0.000    0.001    0.000 astype.py:191(astype_array_safe)
        1    0.000    0.000    0.000    0.000 astype.py:249(astype_is_view)
       19    0.000    0.000    0.001    0.000 astype.py:56(_astype_nansafe)
        1    0.000    0.000    0.001    0.001 asyncio.py:200(_handle_events)
        1    0.000    0.000    0.000    0.000 asyncio.py:225(add_callback)
    15850    0.010    0.000    0.010    0.000 attribute.py:2(__init__)
       35    0.000    0.000    0.000    0.000 attribute_page.py:2(__init__)
    15850    0.016    0.000    0.016    0.000 attribute_page.py:9(add)
        4    0.000    0.000    0.000    0.000 attrsettr.py:42(__getattr__)
        4    0.000    0.000    0.000    0.000 attrsettr.py:65(_get_attr_opt)
      149    0.000    0.000    0.001    0.000 base.py:1017(view)
       47    0.000    0.000    0.002    0.000 base.py:1023(unique)
        1    0.000    0.000    0.000    0.000 base.py:115(reindex_axis)
       52    0.000    0.000    0.002    0.000 base.py:1153(take)
      117    0.000    0.000    0.000    0.000 base.py:1183(_maybe_disallow_fill)
        4    0.000    0.000    0.000    0.000 base.py:123(_reset_cache)
        1    0.000    0.000    0.000    0.000 base.py:1245(repeat)
        9    0.000    0.000    0.000    0.000 base.py:1257(copy)
        2    0.000    0.000    0.000    0.000 base.py:1380(_arith_method)
        4    0.000    0.000    0.000    0.000 base.py:152(na_value)
        4    0.000    0.000    0.000    0.000 base.py:160(_freeze)
       40    0.000    0.000    0.000    0.000 base.py:167(__setattr__)
      367    0.000    0.000    0.000    0.000 base.py:1678(name)
       12    0.000    0.000    0.000    0.000 base.py:1704(_validate_names)
        1    0.000    0.000    0.000    0.000 base.py:1737(_get_default_index_names)
       15    0.000    0.000    0.001    0.000 base.py:176(isna)
       55    0.000    0.000    0.000    0.000 base.py:1772(_get_names)
        5    0.000    0.000    0.000    0.000 base.py:1775(_set_names)
        5    0.000    0.000    0.000    0.000 base.py:1816(set_names)
        5    0.000    0.000    0.000    0.000 base.py:1929(rename)
       18    0.000    0.000    0.000    0.000 base.py:1986(nlevels)
       11    0.000    0.000    0.000    0.000 base.py:2236(is_monotonic_increasing)
       74    0.000    0.000    0.002    0.000 base.py:2320(is_unique)
      286    0.000    0.000    0.000    0.000 base.py:238(construct_from_string)
        1    0.000    0.000    0.000    0.000 base.py:267(replace_list)
        2    0.000    0.000    0.001    0.000 base.py:269(join)
       85    0.001    0.000    0.001    0.000 base.py:2751(inferred_type)
      130    0.000    0.000    0.000    0.000 base.py:2783(_is_multi)
       20    0.000    0.000    0.000    0.000 base.py:2801(_na_value)
        5    0.000    0.000    0.000    0.000 base.py:3042(unique)
        4    0.000    0.000    0.000    0.000 base.py:3078(drop_duplicates)

### Run pipeline

In [45]:
inputid='QYSXJUFSXHHAJI-YRZJJWOYSA-N'
#inputid=5280795

In [46]:
if 'pubchem_files' in locals():
    C2P = Comp2Prot('local', dbs=dbs, pubchem_files=pubchem_files)
    print('Using local copy of PubChem')
else:
    C2P = Comp2Prot('local', dbs=dbs) 
    print('Using PubChem API')

Using local copy of PubChem

In [47]:
[comp_dat,states]=C2P.comp_interactions(input_id=inputid,merge_stereoisomers=False,verbose=False)

In [48]:
comp_dat

,input_id,pc_inchi,pc_inchikey,pc_firstblock,pc_iso_smiles,pc_iupac_name,pc_cid,db_inchikey,entrez,gene_type,...,src_count,pubchem,chembl,bindingdb,stitch,ctd,dtc,otp,drugcentral,drugbank
0,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,246,protein_coding,...,1,1,0,0,0,0,0,0,0,0
1,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,1576,protein_coding,...,2,1,0,0,0,0,0,0,0,1
2,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,2099,protein_coding,...,1,1,0,0,0,0,0,0,0,0
3,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,2741,protein_coding,...,3,1,1,0,0,0,1,0,0,0
4,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,4137,protein_coding,...,1,1,0,0,0,0,0,0,0,0
5,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,4780,protein_coding,...,1,1,0,0,0,0,0,0,0,0
6,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,6097,protein_coding,...,1,1,0,0,0,0,0,0,0,0
7,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,7421,protein_coding,...,8,1,1,1,0,1,1,1,1,1
8,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,51053,protein_coding,...,1,1,0,0,0,0,0,0,0,0
9,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,572,protein_coding,...,1,0,0,0,0,1,0,0,0,0
10,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,598,protein_coding,...,1,0,0,0,0,1,0,0,0,0
11,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,8678,protein_coding,...,1,0,0,0,0,1,0,0,0,0
12,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,1017,protein_coding,...,1,0,0,0,0,1,0,0,0,0
13,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,1027,protein_coding,...,1,0,0,0,0,1,0,0,0,0
14,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,5289,protein_coding,...,1,0,0,0,0,1,0,0,0,0
15,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,5914,protein_coding,...,1,0,0,0,0,1,0,0,0,0
16,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,6256,protein_coding,...,1,0,0,0,0,1,0,0,0,0
17,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,120227,protein_coding,...,1,0,0,0,0,0,0,0,0,1
18,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,1593,protein_coding,...,1,0,0,0,0,0,0,0,0,1
19,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,1573,protein_coding,...,1,0,0,0,0,0,0,0,0,1
20,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,1583,protein_coding,...,1,0,0,0,0,0,0,0,0,1
21,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,1543,protein_coding,...,1,0,0,0,0,0,0,0,0,1
22,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,1558,protein_coding,...,1,0,0,0,0,0,0,0,0,1
23,QYSXJUFSXHHAJI-YRZJJWOYSA-N,InChI=1S/C27H44O/c1-19(2)8-6-9-21(4)25-15-16-2...,QYSXJUFSXHHAJI-YRZJJWOYSA-N,QYSXJUFSXHHAJI,None,"(1S,3Z)-3-[(2E)-2-[(1R,3aS,7aR)-7a-methyl-1-[(...",5280795,QYSXJUFSXHHAJI-YRZJJWOYSA-N,2638,protein_coding,...,1,0,0,0,0,0,0,0,0,1

In [49]:
states

,comp,pc,chembl,bdb,stitch,ctd,dtc,otp,dc,db
0,QYSXJUFSXHHAJI-YRZJJWOYSA-N,completed (local),completed,completed,Filter reduced interactions to 0,completed,completed,completed,completed,completed

### Comp2Prot with select Databases

In [50]:
if 'pubchem_files' in locals():
    C2P = Comp2Prot('local', dbs=dbs, pubchem_files=pubchem_files)
    print('Using local copy of PubChem')
else:
    C2P = Comp2Prot('local', dbs=dbs) 
    print('Using PubChem API')

Using local copy of PubChem

In [51]:
inputid='KSMVNVHUTQZITP-UHFFFAOYSA-N'
#inputid=39929

In [52]:
#The second argument is a string listing the databases needed.
#Underscore is required to separate the databases, if using more than one database.
[comp_dat,states]=C2P.comp_interactions_select(inputid,'ctd_dtc',merge_stereoisomers=False,verbose=False)

In [53]:
comp_dat

,input_id,pc_inchi,pc_inchikey,pc_firstblock,pc_iso_smiles,pc_iupac_name,pc_cid,db_inchikey,entrez,gene_type,...,src_count,pubchem,chembl,bindingdb,stitch,ctd,dtc,otp,drugcentral,drugbank
0,KSMVNVHUTQZITP-UHFFFAOYSA-N,InChI=1S/C12H4Cl4O/c13-7-1-5-6-2-8(14)10(16)4-...,KSMVNVHUTQZITP-UHFFFAOYSA-N,KSMVNVHUTQZITP,None,"2,3,7,8-tetrachlorodibenzofuran",39929,KSMVNVHUTQZITP-UHFFFAOYSA-N,196,protein_coding,...,2,0,0,0,0,1,1,0,0,0
1,KSMVNVHUTQZITP-UHFFFAOYSA-N,InChI=1S/C12H4Cl4O/c13-7-1-5-6-2-8(14)10(16)4-...,KSMVNVHUTQZITP-UHFFFAOYSA-N,KSMVNVHUTQZITP,None,"2,3,7,8-tetrachlorodibenzofuran",39929,KSMVNVHUTQZITP-UHFFFAOYSA-N,405,protein_coding,...,1,0,0,0,0,1,0,0,0,0
2,KSMVNVHUTQZITP-UHFFFAOYSA-N,InChI=1S/C12H4Cl4O/c13-7-1-5-6-2-8(14)10(16)4-...,KSMVNVHUTQZITP-UHFFFAOYSA-N,KSMVNVHUTQZITP,None,"2,3,7,8-tetrachlorodibenzofuran",39929,KSMVNVHUTQZITP-UHFFFAOYSA-N,2033,protein_coding,...,1,0,0,0,0,1,0,0,0,0
3,KSMVNVHUTQZITP-UHFFFAOYSA-N,InChI=1S/C12H4Cl4O/c13-7-1-5-6-2-8(14)10(16)4-...,KSMVNVHUTQZITP-UHFFFAOYSA-N,KSMVNVHUTQZITP,None,"2,3,7,8-tetrachlorodibenzofuran",39929,KSMVNVHUTQZITP-UHFFFAOYSA-N,8648,protein_coding,...,1,0,0,0,0,1,0,0,0,0

In [54]:
states

,comp,pc,chembl,bdb,stitch,ctd,dtc,otp,dc,db
0,KSMVNVHUTQZITP-UHFFFAOYSA-N,Did not run pc,Did not run chembl,Did not run bdb,Did not run stitch,completed,completed,Did not run otp,Did not run dc,Did not run db

# Run each step/database separately (for troubleshooting)

In [3]:
from cpiextract.databases import *
from cpiextract.utils import compound_identifiers
inputid='FPIPGXGPPPQFEQ-OVSJKPMPSA-N'
#inputid=445354
comp_ids=compound_identifiers(inputid)

In [4]:
comp_ids

,isomeric_smiles,canonical_smiles,inchi,inchikey,synonyms,iupac_name,molecular_formula,molecular_weight,cid,inchikey_fb
0,None,None,InChI=1S/C20H30O/c1-16(8-6-9-17(2)13-15-21)11-...,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,"[retinol, all-trans-Retinol, 68-26-8, trans-re...","(2E,4E,6E,8E)-3,7-dimethyl-9-(2,6,6-trimethylc...",C20H30O,286.5,445354,FPIPGXGPPPQFEQ

### Run PubChem only

In [ ]:
#Local PubChem will improve speed. Only run if you have the resources for a local pubchem.
data_path='data/Databases/'
file_path=os.path.join(data_path,'pubchem.duckdb')

In [5]:
if 'file_path' in locals():
    pubchem=PubChem(bioact_file=file_path)
    print('Using local copy of PubChem')
else:
    pubchem=PubChem()
    print('Using PubChem API')

[pc_dat,pc_state,pc_raw]=pubchem.interactions(input_comp=comp_ids,pChEMBL_thres=0,merge_stereoisomers=False,verbose=False)

Using PubChem API

In [6]:
pc_dat

,AID,Panel Member ID,SID,CID,Activity Outcome,Target Accession,Target GeneID,Activity Value [uM],Activity Name,Assay Name,...,RNAi,pchembl_value,GeneID,TaxonomyID,inchikey,entrez,gene_type,hgnc_symbol,description,datasource
0,588514,,26753110,445354,Active,AEP43755,2099,3.16230,Potency,qHTS assay for small molecule agonists of estr...,...,,5.499997,2099,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,2099.0,protein_coding,ESR1,estrogen receptor 1 [Source:HGNC Symbol;Acc:HG...,PubChem
1,588834,,17389530,445354,Active,NP_001191727,3757,14.12540,Potency,qHTS Assay for Small Molecule Inhibitors of th...,...,,4.849999,3757,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,3757.0,protein_coding,KCNH2,potassium voltage-gated channel subfamily H me...,PubChem
2,606062,,103260440,445354,Active,P02753,5950,0.18200,Kd,Binding affinity to His-tagged recombinant hum...,...,,6.739929,5950,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,5950.0,protein_coding,RBP4,retinol binding protein 4 [Source:HGNC Symbol;...,PubChem
3,651741,,17389530,445354,Active,NP_006155,4780,42.16320,Potency,qHTS assay for small molecule agonists of the ...,...,,4.375066,4780,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,4780.0,protein_coding,NFE2L2,NFE2 like bZIP transcription factor 2 [Source:...,PubChem
4,651741,,144204369,445354,Active,NP_006155,4780,68.58960,Potency,qHTS assay for small molecule agonists of the ...,...,,4.163742,4780,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,4780.0,protein_coding,NFE2L2,NFE2 like bZIP transcription factor 2 [Source:...,PubChem
5,651758,,17389530,445354,Active,AAA59158,3576,37.57800,Potency,qHTS assay to identify small molecules that st...,...,,4.425066,3576,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,3576.0,protein_coding,CXCL8,C-X-C motif chemokine ligand 8 [Source:HGNC Sy...,PubChem
6,720659,,17389530,445354,Active,ADZ17384,8856,2.81840,Potency,qHTS assay for small molecule activators of th...,...,,5.549997,8856,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,8856.0,protein_coding,NR1I2,nuclear receptor subfamily 1 group I member 2 ...,PubChem
7,720659,,26753110,445354,Active,ADZ17384,8856,7.07950,Potency,qHTS assay for small molecule activators of th...,...,,5.149997,8856,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,8856.0,protein_coding,NR1I2,nuclear receptor subfamily 1 group I member 2 ...,PubChem
8,720692,,144209639,445354,Active,ADP91253,2908,55.63410,Potency,qHTS assay to identify small molecule antagoni...,...,,4.254659,2908,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,2908.0,protein_coding,NR3C1,nuclear receptor subfamily 3 group C member 1 ...,PubChem
9,743042,,144209639,445354,Active,AAI32976,367,61.87730,Potency,qHTS assay to identify small molecule antagoni...,...,,4.208469,367,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,367.0,protein_coding,AR,androgen receptor [Source:HGNC Symbol;Acc:HGNC...,PubChem
10,743054,,144210607,445354,Active,AAI32976,367,72.30290,Potency,qHTS assay to identify small molecule antagoni...,...,,4.140844,367,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,367.0,protein_coding,AR,androgen receptor [Source:HGNC Symbol;Acc:HGNC...,PubChem
11,743075,,144204369,445354,Active,AEP43755,2099,8.48520,Potency,qHTS assay to identify small molecule agonists...,...,,5.071338,2099,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,2099.0,protein_coding,ESR1,estrogen receptor 1 [Source:HGNC Symbol;Acc:HG...,PubChem
12,743077,,144204369,445354,Active,AEP43755,2099,20.49130,Potency,qHTS assay to identify small molecule agonists...,...,,4.688430,2099,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,2099.0,protein_coding,ESR1,estrogen receptor 1 [Source:HGNC Symbol;Acc:HG...,PubChem
13,743079,,144204369,445354,Active,AEP43755,2099,0.94390,Potency,qHTS assay to identify small molecule agonists...,...,,6.025074,2099,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,2099.0,protein_coding,ESR1,estrogen receptor 1 [Source:HGNC Symbol;Acc:HG...,PubChem
14,743080,,144204369,445354,Active,AEP43755,2099,14.96010,Potency,qHTS assay to identify small molecule antagoni...,...,,4.825066,2099,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,2099.0,protein_coding,ESR1,estrogen receptor 1 [Source:HGNC Symbol;Acc:HG...,PubChem
15,743080,,144209639,445354,Active,AEP43755,2099,7.78990,Potency,qHTS assay to identify small molecule antagoni...,...,,5.108468,2099,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,2099.0,protein_coding,ESR1,estrogen receptor 1 [Source:HGNC Symbol;Acc:HG...,PubChem
16,743083,,144210607,445354,Active,EAW77416,1588,28.78430,Potency,qHTS assay to identify aromatase inhibitors,...,,4.540844,1588,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,1588.0,protein_coding,CYP19A1,cytochrome P450 family 19 subfamily A member 1...,PubChem
17,743091,,144204369,445354,Active,AEP43755,2099,23.71010,Potency,qHTS assay to identify small molecule antagoni...,...,,4.625067,2099,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,2099.0,protein_coding,ESR1,estrogen receptor 1 [Source:HGNC Symbol;Acc:HG...,PubChem
18,743091,,144209639,445354,Active,AEP43755,2099,18.12170,Potency,qHTS assay to identify small molecule antagoni...,...,,4.741801,2099,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,2099.0,protein_coding,ESR1,estrogen receptor 1 [Source:HGNC Symbol;Acc:HG...,PubChem
19,743202,,144209639,445354,Active,NP_006155,4780,61.87730,Potency,qHTS assay for small molecule agonists of the ...,...,,4.208469,4780,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,4780.0,protein_coding,NFE2L2,NFE2 like bZIP transcription factor 2 [Source:...,PubChem
20,743202,,144210607,445354,Active,NP_006155,4780,57.43220,Potency,qHTS assay for small molecule agonists of the ...,...,,4.240845,4780,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,4780.0,protein_coding,NFE2L2,NFE2 like bZIP transcription factor 2 [Source:...,PubChem
21,743219,,144210607,445354,Active,NP_006155,4780,59.67910,Potency,qHTS assay for small molecule agonists of the ...,...,,4.224178,4780,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,4780.0,protein_coding,NFE2L2,NFE2 like bZIP transcription factor 2 [Source:...,PubChem
22,743228,,144209639,445354,Active,NP_001531,3315,49.58390,Potency,qHTS assay for small molecule activators of th...,...,,4.304659,3315,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,3315.0,protein_coding,HSPB1,heat shock protein family B (small) member 1 [...,PubChem
23,743228,,144210607,445354,Active,NP_001531,3315,60.19150,Potency,qHTS assay for small molecule activators of th...,...,,4.220465,3315,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,3315.0,protein_coding,HSPB1,heat shock protein family B (small) member 1 [...,PubChem
24,1159531,,144209639,445354,Active,ADZ17354,6256,3.31391,Potency,qHTS assay to identify small molecule agonists...,...,,5.479659,6256,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,6256.0,protein_coding,RXRA,retinoid X receptor alpha [Source:HGNC Symbol;...,PubChem
25,1159531,,144210607,445354,Active,ADZ17354,6256,4.34379,Potency,qHTS assay to identify small molecule agonists...,...,,5.362131,6256,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,6256.0,protein_coding,RXRA,retinoid X receptor alpha [Source:HGNC Symbol;...,PubChem
26,1159553,,144209639,445354,Active,ADZ17337,5914,13.85260,Potency,qHTS assay to identify small molecule agonists...,...,,4.858469,5914,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,5914.0,protein_coding,RARA,retinoic acid receptor alpha [Source:HGNC Symb...,PubChem
27,1159553,,144210607,445354,Active,ADZ17337,5914,32.29650,Potency,qHTS assay to identify small molecule agonists...,...,,4.490845,5914,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,5914.0,protein_coding,RARA,retinoic acid receptor alpha [Source:HGNC Symb...,PubChem
28,1259243,,144210607,445354,Active,AAI32976,367,57.43220,Potency,qHTS assay to identify small molecule antagoni...,...,,4.240845,367,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,367.0,protein_coding,AR,androgen receptor [Source:HGNC Symbol;Acc:HGNC...,PubChem
29,1259369,,144209639,445354,Active,AAI13617,2737,15.54290,Potency,qHTS assay to identify small molecule antagoni...,...,,4.808468,2737,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,2737.0,protein_coding,GLI3,GLI family zinc finger 3 [Source:HGNC Symbol;A...,PubChem
30,1259378,,144210607,445354,Active,AAV31779,2100,64.44000,Potency,qHTS assay to identify small molecule antagoni...,...,,4.190844,2100,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,2100.0,protein_coding,ESR2,estrogen receptor 2 [Source:HGNC Symbol;Acc:HG...,PubChem
31,1259392,,144209639,445354,Active,AAI13617,2737,20.72680,Potency,qHTS assay to identify small molecule antagoni...,...,,4.683468,2737,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,2737.0,protein_coding,GLI3,GLI family zinc finger 3 [Source:HGNC Symbol;A...,PubChem
32,1259392,,144210607,445354,Active,AAI13617,2737,9.45850,Potency,qHTS assay to identify small molecule antagoni...,...,,5.024178,2737,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,2737.0,protein_coding,GLI3,GLI family zinc finger 3 [Source:HGNC Symbol;A...,PubChem
33,1346982,,144209639,445354,Active,ADZ17384,8856,55.14820,Potency,Human pregnane X receptor (PXR) small molecule...,...,,4.258469,8856,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,8856.0,protein_coding,NR1I2,nuclear receptor subfamily 1 group I member 2 ...,PubChem
34,1346982,,144210607,445354,Active,ADZ17384,8856,32.29650,Potency,Human pregnane X receptor (PXR) small molecule...,...,,4.490845,8856,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,8856.0,protein_coding,NR1I2,nuclear receptor subfamily 1 group I member 2 ...,PubChem
35,1671197,,144209639,445354,Active,,1557,50.90650,Potency,Cytochrome P450 Family 2 Subfamily C Member 19...,...,,4.293227,1557,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,1557.0,protein_coding,CYP2C19,cytochrome P450 family 2 subfamily C member 19...,PubChem
36,1671197,,144210607,445354,Active,,1557,37.49800,Potency,Cytochrome P450 Family 2 Subfamily C Member 19...,...,,4.425992,1557,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,1557.0,protein_coding,CYP2C19,cytochrome P450 family 2 subfamily C member 19...,PubChem
37,1671198,,144209639,445354,Active,,1559,64.08750,Potency,Cytochrome P450 Family 2 Subfamily C Member 9 ...,...,,4.193227,1559,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,1559.0,protein_coding,CYP2C9,cytochrome P450 family 2 subfamily C member 9 ...,PubChem
38,1671198,,144210607,445354,Active,,1559,37.49800,Potency,Cytochrome P450 Family 2 Subfamily C Member 9 ...,...,,4.425992,1559,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,1559.0,protein_coding,CYP2C9,cytochrome P450 family 2 subfamily C member 9 ...,PubChem
39,1671199,,144209639,445354,Active,,1544,20.26620,Potency,Cytochrome P450 Family 1 Subfamily A Member 2 ...,...,,4.693228,1544,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,1544.0,protein_coding,CYP1A2,cytochrome P450 family 1 subfamily A member 2 ...,PubChem
40,1671201,,144209639,445354,Active,,1576,18.06230,Potency,Cytochrome P450 Family 3 Subfamily A Member 4 ...,...,,4.743227,1576,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,1576.0,protein_coding,CYP3A4,cytochrome P450 family 3 subfamily A member 4 ...,PubChem
41,1671201,,144210607,445354,Active,,1576,11.85790,Potency,Cytochrome P450 Family 3 Subfamily A Member 4 ...,...,,4.925992,1576,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,1576.0,protein_coding,CYP3A4,cytochrome P450 family 3 subfamily A member 4 ...,PubChem
42,1695730,,103260440,445354,Active,P37840,6622,0.19000,IC50,Inhibition of alpha-synuclein fibril formation...,...,,6.721246,6622,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,6622.0,protein_coding,SNCA,synuclein alpha [Source:HGNC Symbol;Acc:HGNC:1...,PubChem
43,1695748,,103260440,445354,Active,P05067,351,0.18000,IC50,Inhibition of amyloid beta (1 to 40) (unknown ...,...,,6.744727,351,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,351.0,protein_coding,APP,amyloid beta precursor protein [Source:HGNC Sy...,PubChem
44,1845192,,405558473,445354,Active,,2879,17.78280,Potency,Primary qHTS Assay for Inhibitors of Recombina...,...,,4.750000,2879,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,2879.0,protein_coding,GPX4,glutathione peroxidase 4 [Source:HGNC Symbol;A...,PubChem
45,1919969,,144209639,445354,Active,,4780,69.42750,Potency,Nuclear factor erythroid 2-related factor 2/an...,...,,4.158468,4780,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,4780.0,protein_coding,NFE2L2,NFE2 like bZIP transcription factor 2 [Source:...,PubChem
46,1919969,,144210607,445354,Active,,4780,72.30290,Potency,Nuclear factor erythroid 2-related factor 2/an...,...,,4.140844,4780,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,4780.0,protein_coding,NFE2L2,NFE2 like bZIP transcription factor 2 [Source:...,PubChem
47,1919973,,472319443,445354,Active,,1559,14.12540,Potency,qHTS for inhibitors of CYP2C9 against the NCAT...,...,,4.849999,1559,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,1559.0,protein_coding,CYP2C9,cytochrome P450 family 2 subfamily C member 9 ...,PubChem
48,1961803,,103260440,445354,Active,O75469,8856,4.80000,AC50,Binding affinity towards human NR1I2 in an in ...,...,,5.318759,8856,9606,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,8856.0,protein_coding,NR1I2,nuclear receptor subfamily 1 group I member 2 ...,PubChem

In [7]:
pc_state

'completed (API)'

### Run ChEMBL only

In [9]:
chembl_ids = []

In [10]:
file_path=os.path.join(data_path, 'ChEMBL_Dec2025.csv')
chembl_data=pd.read_csv(file_path,sep=',',low_memory=False,index_col=0)

In [12]:
chembl=ChEMBL(database=chembl_data)
[chembl_dat,chembl_state,chembl_raw]=chembl.interactions(input_comp=comp_ids,pChEMBL_thres=0,
                                                         chembl_ids=chembl_ids,merge_stereoisomers=False)

In [13]:
chembl_dat

,Molecule ChEMBL ID,inchikey,CID,Comment,Data Validity Comment,Target Organism,Source ID,pchembl_value,Target ChEMBL ID,Target Type,entrez,gene_type,hgnc_symbol,description,datasource
0,CHEMBL986,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,445354,NaN,NaN,Homo sapiens,1,6.74,CHEMBL3100,SINGLE PROTEIN,5950.0,protein_coding,RBP4,retinol binding protein 4 [Source:HGNC Symbol;...,ChEMBL
1,CHEMBL986,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,445354,NaN,NaN,Homo sapiens,1,6.72,CHEMBL6152,SINGLE PROTEIN,6622.0,protein_coding,SNCA,synuclein alpha [Source:HGNC Symbol;Acc:HGNC:1...,ChEMBL
2,CHEMBL986,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,445354,NaN,NaN,Homo sapiens,1,6.75,CHEMBL2487,SINGLE PROTEIN,351.0,protein_coding,APP,amyloid beta precursor protein [Source:HGNC Sy...,ChEMBL

In [14]:
chembl_state

'completed'

### Run BindingDB only

In [15]:
file_path=os.path.join(data_path, 'BindingDB_Dec2025.csv')
BDB_data=pd.read_csv(file_path,sep=',',low_memory=False,index_col=0)

In [16]:
bdb=BindingDB(database=BDB_data)
[bdb_dat,bdb_state,bdb_raw]=bdb.interactions(input_comp=comp_ids,pChEMBL_thres=0,merge_stereoisomers=False)

In [19]:
bdb_dat

,old_inchikey,BindingDB MonomerID,BindingDB Ligand Name,Target Name Assigned by Curator or DataSource,Target Source Organism According to Curator or DataSource,pH,Temp (C),Curation/DataSource,UniProt (SwissProt) Entry Name of Target Chain,UniProt (SwissProt) Primary ID of Target Chain,CID,inchikey,FirstBlock,pchembl_value,notes,entrez,gene_type,hgnc_symbol,description,datasource
0,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,50092056,"(2E,4E,6E,8E)-3,7-dimethyl-9-(2,6,6-trimethylc...",Amyloid-beta precursor protein,Homo sapiens,NaN,NaN,ChEMBL,A4_HUMAN,P05067,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,6.744727,IC50 (nM),351.0,protein_coding,APP,amyloid beta precursor protein [Source:HGNC Sy...,BindingDB

In [20]:
bdb_state

'completed'

### Run STITCH only

In [21]:
file_path=os.path.join(data_path,'STITCH.csv')
sttch_data=pd.read_csv(file_path,sep=',',low_memory=False,index_col=0)

In [22]:
stitch=Stitch(database=sttch_data)
[sttch_dat,sttch_state,sttch_raw]=stitch.interactions(input_comp=comp_ids,merge_stereoisomers=False)

In [23]:
sttch_dat

,chemical,protein,experimental,prediction,database,textmining,combined_score,CID,inchikey,FirstBlock,String_id,String_symbol,entrez,gene_type,hgnc_symbol,description,datasource,pchembl_value
0,CIDs00445354,9606.ENSP00000222271,795,0,0,0,795,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000222271,COMP,1311.0,protein_coding,COMP,cartilage oligomeric matrix protein [Source:HG...,Stitch,NaN
1,CIDs00445354,9606.ENSP00000232217,832,0,900,807,996,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000232217,RBP2,5948.0,protein_coding,RBP2,retinol binding protein 2 [Source:HGNC Symbol;...,Stitch,NaN
2,CIDs00445354,9606.ENSP00000232219,185,0,900,916,992,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000232219,RBP1,NaN,None,None,None,Stitch,NaN
3,CIDs00445354,9606.ENSP00000237014,800,0,900,690,993,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000237014,TTR,7276.0,protein_coding,TTR,transthyretin [Source:HGNC Symbol;Acc:HGNC:12405],Stitch,NaN
4,CIDs00445354,9606.ENSP00000256103,185,0,0,309,421,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000256103,PMP2,5375.0,protein_coding,PMP2,peripheral myelin protein 2 [Source:HGNC Symbo...,Stitch,NaN
5,CIDs00445354,9606.ENSP00000256104,185,0,0,122,263,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000256104,FABP4,2167.0,protein_coding,FABP4,fatty acid binding protein 4 [Source:HGNC Symb...,Stitch,NaN
6,CIDs00445354,9606.ENSP00000260356,658,0,0,0,658,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000260356,THBS1,7057.0,protein_coding,THBS1,thrombospondin 1 [Source:HGNC Symbol;Acc:HGNC:...,Stitch,NaN
7,CIDs00445354,9606.ENSP00000266560,185,0,900,700,974,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000266560,RBP5,83758.0,protein_coding,RBP5,retinol binding protein 5 [Source:HGNC Symbol;...,Stitch,NaN
8,CIDs00445354,9606.ENSP00000274024,185,0,0,224,350,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000274024,FABP2,2169.0,protein_coding,FABP2,fatty acid binding protein 2 [Source:HGNC Symb...,Stitch,NaN
9,CIDs00445354,9606.ENSP00000277508,773,0,0,168,805,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000277508,NaN,5047.0,protein_coding,PAEP,progestagen associated endometrial protein [So...,Stitch,NaN
10,CIDs00445354,9606.ENSP00000294435,185,0,0,496,577,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000294435,RBP7,116362.0,protein_coding,RBP7,retinol binding protein 7 [Source:HGNC Symbol;...,Stitch,NaN
11,CIDs00445354,9606.ENSP00000295834,185,0,0,114,257,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000295834,FABP1,2168.0,protein_coding,FABP1,fatty acid binding protein 1 [Source:HGNC Symb...,Stitch,NaN
12,CIDs00445354,9606.ENSP00000297258,185,0,0,266,385,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000297258,FABP5,2171.0,protein_coding,FABP5,fatty acid binding protein 5 [Source:HGNC Symb...,Stitch,NaN
13,CIDs00445354,9606.ENSP00000299529,185,0,0,827,855,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000299529,CRABP1,1381.0,protein_coding,CRABP1,cellular retinoic acid binding protein 1 [Sour...,Stitch,NaN
14,CIDs00445354,9606.ENSP00000339730,705,0,0,0,705,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000339730,THBS4,7060.0,protein_coding,THBS4,thrombospondin 4 [Source:HGNC Symbol;Acc:HGNC:...,Stitch,NaN
15,CIDs00445354,9606.ENSP00000353650,185,0,0,118,261,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000353650,FABP12,646486.0,protein_coding,FABP12,fatty acid binding protein 12 [Source:HGNC Sym...,Stitch,NaN
16,CIDs00445354,9606.ENSP00000355751,658,0,0,0,658,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000355751,THBS2,7058.0,protein_coding,THBS2,thrombospondin 2 [Source:HGNC Symbol;Acc:HGNC:...,Stitch,NaN
17,CIDs00445354,9606.ENSP00000357204,185,0,150,597,704,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000357204,NaN,1382.0,protein_coding,CRABP2,cellular retinoic acid binding protein 2 [Sour...,Stitch,NaN
18,CIDs00445354,9606.ENSP00000357362,705,0,0,0,705,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000357362,THBS3,7059.0,protein_coding,THBS3,thrombospondin 3 [Source:HGNC Symbol;Acc:HGNC:...,Stitch,NaN
19,CIDs00445354,9606.ENSP00000357429,185,0,0,0,185,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000357429,FABP7,2173.0,protein_coding,FABP7,fatty acid binding protein 7 [Source:HGNC Symb...,Stitch,NaN
20,CIDs00445354,9606.ENSP00000360519,800,0,900,738,994,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000360519,NaN,5950.0,protein_coding,RBP4,retinol binding protein 4 [Source:HGNC Symbol;...,Stitch,NaN
21,CIDs00445354,9606.ENSP00000362817,185,0,0,0,185,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000362817,FABP3,2170.0,protein_coding,FABP3,fatty acid binding protein 3 [Source:HGNC Symb...,Stitch,NaN
22,CIDs00445354,9606.ENSP00000368362,185,0,0,118,260,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000368362,FABP9,646480.0,protein_coding,FABP9,fatty acid binding protein 9 [Source:HGNC Symb...,Stitch,NaN
23,CIDs00445354,9606.ENSP00000377549,185,0,0,0,185,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,ENSP00000377549,FABP6,2172.0,protein_coding,FABP6,fatty acid binding protein 6 [Source:HGNC Symb...,Stitch,NaN

In [24]:
sttch_state

'completed'

### Run CTD only

In [25]:
file_path=os.path.join(data_path, 'CTD_Dec2025.csv')
CTD_data=pd.read_csv(file_path,sep=',',low_memory=False,index_col=0)

In [26]:
ctd = CTD(database=CTD_data)
[ctd_dat,ctd_state,ctd_raw]=ctd.interactions(input_comp=comp_ids,merge_stereoisomers=False)

In [27]:
ctd_dat

Empty DataFrame
Columns: [entrez, gene_type, hgnc_symbol, description, pchembl_value, datasource]
Index: []

In [28]:
ctd_state

'No interaction data'

### Run DTC only

In [29]:
file_path=os.path.join(data_path, 'DTC_Dec2025.csv')
DTC_data=pd.read_csv(file_path,sep=',',low_memory=False,index_col=0)

In [30]:
dtc=DTC(database=DTC_data)
[dtc_dat,dtc_state,dtc_raw]=dtc.interactions(input_comp=comp_ids,chembl_ids=[],
                                             pChEMBL_thres=0,merge_stereoisomers=False)

In [31]:
dtc_dat

,compound_id,target_id,gene_names,wildtype_or_mutant,mutation_info,standard_type,standard_relation,standard_value,standard_units,activity_comment,...,inchikey,FirstBlock,molecular_weight,standardized_val,pchembl_value,entrez,gene_type,hgnc_symbol,description,datasource
0,CHEMBL986,P02754,NaN,NaN,NaN,KD,=,36.0,NM,NaN,...,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,286.5,36.0,7.443697,None,None,None,None,DTC
1,CHEMBL986,P02753,RBP4,NaN,NaN,KD,=,182.0,NM,NaN,...,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,286.5,182.0,6.739929,5950,protein_coding,RBP4,retinol binding protein 4 [Source:HGNC Symbol;...,DTC

In [32]:
dtc_state

'completed'

### Run OTP only

In [33]:
file_path=os.path.join(data_path, 'OTP_Dec2025.csv')
OTP_data=pd.read_csv(file_path, sep=',',low_memory=False,index_col=0)

In [34]:
otp=OTP(database=OTP_data)
[otp_dat,otp_state,otp_raw]=otp.interactions(input_comp=comp_ids,chembl_ids=[],merge_stereoisomers=False)

In [35]:
otp_dat

Empty DataFrame
Columns: [entrez, gene_type, hgnc_symbol, description, pchembl_value, datasource]
Index: []

In [38]:
otp_state

'No ChEMBL ids found in local OTP'

### Run DrugCentral only

In [42]:
file_path=os.path.join(data_path, 'DrugCentral_Dec2025.csv')
DC_data=pd.read_csv(file_path, sep=',',low_memory=False,index_col=0)

In [43]:
dc=DrugCentral(database=DC_data)
[DC_dat,DC_state,DC_raw]=dc.interactions(input_comp=comp_ids,merge_stereoisomers=False)

In [44]:
DC_dat

,DRUG_NAME,STRUCT_ID,TARGET_NAME,TARGET_CLASS,ACCESSION,GENE,SWISSPROT,ACT_VALUE,ACT_UNIT,notes,...,ORGANISM,CID,inchikey,FirstBlock,pchembl_value,entrez,gene_type,hgnc_symbol,description,datasource
0,retinol,2831,Nuclear receptor subfamily 2 group C member 2,Nuclear other,P49116,NR2C2,NR2C2_HUMAN,4.71,NaN,EC50,...,Homo sapiens,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,8.326979,7182.0,protein_coding,NR2C2,nuclear receptor subfamily 2 group C member 2 ...,DrugCentral

In [45]:
DC_state

'completed'

### Run DrugBank only

In [46]:
file_path=os.path.join(data_path, 'DB_Dec2025.csv')
DB_data=pd.read_csv(file_path, sep=',',low_memory=False,index_col=0)

In [47]:
db=DB(database=DB_data)
[DB_dat,DB_state,DB_raw]=db.interactions(input_comp=comp_ids,merge_stereoisomers=False)

In [48]:
DB_dat

,drugbank-id,name,protein_name,protein_type,organism,HGNC,CID,inchikey,FirstBlock,entrez,gene_type,hgnc_symbol,description,datasource,pchembl_value
0,DB00162,Vitamin A,Retinoic acid receptor RXR-gamma,target,Humans,HGNC:10479,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,6258.0,protein_coding,RXRG,retinoid X receptor gamma [Source:HGNC Symbol;...,DrugBank,NaN
1,DB00162,Vitamin A,Apolipoprotein D,target,Humans,HGNC:612,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,347.0,protein_coding,APOD,apolipoprotein D [Source:HGNC Symbol;Acc:HGNC:...,DrugBank,NaN
2,DB00162,Vitamin A,Prostaglandin-H2 D-isomerase,target,Humans,HGNC:9592,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,5730.0,protein_coding,PTGDS,prostaglandin D2 synthase [Source:HGNC Symbol;...,DrugBank,NaN
3,DB00162,Vitamin A,Retinol dehydrogenase 12,target,Humans,HGNC:19977,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,145226.0,protein_coding,RDH12,retinol dehydrogenase 12 [Source:HGNC Symbol;A...,DrugBank,NaN
4,DB00162,Vitamin A,Retinol dehydrogenase 5,target,Humans,HGNC:9940,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,5959.0,protein_coding,RDH5,retinol dehydrogenase 5 [Source:HGNC Symbol;Ac...,DrugBank,NaN
5,DB00162,Vitamin A,Retinol dehydrogenase 13,target,Humans,HGNC:19978,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,112724.0,protein_coding,RDH13,retinol dehydrogenase 13 [Source:HGNC Symbol;A...,DrugBank,NaN
6,DB00162,Vitamin A,Retinal dehydrogenase 2,target,Humans,HGNC:15472,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,8854.0,protein_coding,ALDH1A2,aldehyde dehydrogenase 1 family member A2 [Sou...,DrugBank,NaN
7,DB00162,Vitamin A,Aldehyde dehydrogenase 1A1,target,Humans,HGNC:402,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,216.0,protein_coding,ALDH1A1,aldehyde dehydrogenase 1 family member A1 [Sou...,DrugBank,NaN
8,DB00162,Vitamin A,Lecithin retinol acyltransferase,target,Humans,HGNC:6685,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,9227.0,protein_coding,LRAT,lecithin retinol acyltransferase [Source:HGNC ...,DrugBank,NaN
9,DB00162,Vitamin A,Short-chain dehydrogenase/reductase 3,target,Humans,HGNC:17693,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,9249.0,protein_coding,DHRS3,dehydrogenase/reductase 3 [Source:HGNC Symbol;...,DrugBank,NaN
10,DB00162,Vitamin A,Retinaldehyde dehydrogenase 3,target,Humans,HGNC:409,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,220.0,protein_coding,ALDH1A3,aldehyde dehydrogenase 1 family member A3 [Sou...,DrugBank,NaN
11,DB00162,Vitamin A,"All-trans-retinol 13,14-reductase",target,Humans,HGNC:25991,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,54884.0,protein_coding,RETSAT,retinol saturase [Source:HGNC Symbol;Acc:HGNC:...,DrugBank,NaN
12,DB00162,Vitamin A,Retinol dehydrogenase 11,target,Humans,HGNC:17964,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,51109.0,protein_coding,RDH11,retinol dehydrogenase 11 [Source:HGNC Symbol;A...,DrugBank,NaN
13,DB00162,Vitamin A,Dehydrogenase/reductase SDR family member 4,target,Humans,HGNC:16985,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,10901.0,protein_coding,DHRS4,dehydrogenase/reductase 4 [Source:HGNC Symbol;...,DrugBank,NaN
14,DB00162,Vitamin A,Retinol dehydrogenase 14,target,Humans,HGNC:19979,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,57665.0,protein_coding,RDH14,retinol dehydrogenase 14 [Source:HGNC Symbol;A...,DrugBank,NaN
15,DB00162,Vitamin A,Retinol dehydrogenase 8,target,Humans,HGNC:14423,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,50700.0,protein_coding,RDH8,retinol dehydrogenase 8 [Source:HGNC Symbol;Ac...,DrugBank,NaN
16,DB00162,Vitamin A,Cytochrome P450 26A1,enzyme,Humans,HGNC:2603,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,1592.0,protein_coding,CYP26A1,cytochrome P450 family 26 subfamily A member 1...,DrugBank,NaN
17,DB00162,Vitamin A,Albumin,carrier,Humans,HGNC:399,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,213.0,protein_coding,ALB,albumin [Source:HGNC Symbol;Acc:HGNC:399],DrugBank,NaN
18,DB00162,Vitamin A,Retinaldehyde-binding protein 1,carrier,Humans,HGNC:10024,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,6017.0,protein_coding,RLBP1,retinaldehyde binding protein 1 [Source:HGNC S...,DrugBank,NaN
19,DB00162,Vitamin A,Retinol-binding protein 3,carrier,Humans,HGNC:9921,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,5949.0,protein_coding,RBP3,retinol binding protein 3 [Source:HGNC Symbol;...,DrugBank,NaN
20,DB00162,Vitamin A,Retinol-binding protein 1,carrier,Humans,HGNC:9919,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,5947.0,protein_coding,RBP1,retinol binding protein 1 [Source:HGNC Symbol;...,DrugBank,NaN
21,DB00162,Vitamin A,Retinol-binding protein 5,carrier,Humans,HGNC:15847,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,83758.0,protein_coding,RBP5,retinol binding protein 5 [Source:HGNC Symbol;...,DrugBank,NaN
22,DB00162,Vitamin A,Retinoid-binding protein 7,carrier,Humans,HGNC:30316,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,116362.0,protein_coding,RBP7,retinol binding protein 7 [Source:HGNC Symbol;...,DrugBank,NaN
23,DB00162,Vitamin A,Retinol-binding protein 4,carrier,Humans,HGNC:9922,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,5950.0,protein_coding,RBP4,retinol binding protein 4 [Source:HGNC Symbol;...,DrugBank,NaN
24,DB00162,Vitamin A,Retinol-binding protein 2,carrier,Humans,HGNC:9920,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,5948.0,protein_coding,RBP2,retinol binding protein 2 [Source:HGNC Symbol;...,DrugBank,NaN
25,DB00162,Vitamin A,Receptor for retinol uptake STRA6,transporter,Humans,HGNC:30650,445354,FPIPGXGPPPQFEQ-OVSJKPMPSA-N,FPIPGXGPPPQFEQ,64220.0,protein_coding,STRA6,signaling receptor and transporter of retinol ...,DrugBank,NaN

In [49]:
DB_state

'completed'