This example notebooks shows the local execution of Prot2Comp and of the singular databases. Note: Download the new database files from the Dropbox link in the data folder Readme.

In [2]:
#General packages
import pandas as pd
from tqdm import tqdm
import os
#from cpiextract import Prot2Comp
import time
import cProfile

In [3]:
# Root data path
data_path = 'data/Databases/'

# Load in Datasets

Datasets which require local copies

In [5]:
#Downloaded from BindingDB on 12/8/2025
file_path=os.path.join(data_path, 'BindingDB_Dec2025.csv')
BDB_data=pd.read_csv(file_path,sep=',',low_memory=False,index_col=0)

#Downloaded from STITCH on 2/22/2023 unchanged on 12/8/2025
file_path=os.path.join(data_path, 'STITCH.csv')
sttch_data=pd.read_csv(file_path,sep=',',low_memory=False,index_col=0)

#Downloaded from CTD 12/8/2025
file_path=os.path.join(data_path, 'CTD_Dec2025.csv')
CTD_data=pd.read_csv(file_path,sep=',',low_memory=False,index_col=0)

#Downloaded from DTC on 2/24/2023 unchanged on 12/8/2025
file_path=os.path.join(data_path, 'DTC_Dec2025.csv')
DTC_data=pd.read_csv(file_path,sep=',',low_memory=False,index_col=0)

#Downloaded from DrugBank on 12/8/2025
file_path=os.path.join(data_path, 'DB_Dec2025.csv')
DB_data=pd.read_csv(file_path, sep=',',low_memory=False,index_col=0)

#Downloaded from DrugCentral on 2/25/2024 unchanged on 12/8/2025
file_path=os.path.join(data_path, 'DrugCentral_Dec2025.csv')
DC_data=pd.read_csv(file_path, sep=',',low_memory=False,index_col=0)

Datasets with APIs or can be run locally for faster speeds

In [6]:
#Downloaded from ChEMBL on 12/8/2025
file_path=os.path.join(data_path, 'ChEMBL_Dec2025.csv')
chembl_data=pd.read_csv(file_path,sep=',',low_memory=False,index_col=0)

#Downloaded from OTP on 2/2/2026
file_path=os.path.join(data_path, 'OTP_Dec2025.csv')
OTP_data=pd.read_csv(file_path, sep=',',low_memory=False,index_col=0)

If you have the resources to run a local copy of PubChem, Otherwise do not run.

In [7]:
#Local PubChem will improve speed
file_path=os.path.join(data_path, 'pubchem/pubchem.duckdb')
pubchem_files = {'db_file': file_path}

Build database dictionary

In [8]:
#Suppress OTP or ChEMBL if local copies are not available
dbs = {
    'chembl': chembl_data,
    'bdb': BDB_data,
    'stitch': sttch_data,
    'ctd': CTD_data,
    'dtc': DTC_data,
    'db': DB_data,
    'dc': DC_data,
    'otp': OTP_data
}

## Load in Protein List

In [9]:
#inputids=pd.read_csv('data/input/db_proteins.csv')
inputids=pd.read_csv(data_path+'db_proteins.csv')
output_path = 'data/output/'

## Run Prot2Comp on Protein List

In [16]:
if 'pubchem_files' in locals():
    P2C = Prot2Comp('local', dbs=dbs, pubchem_files=pubchem_files)
    print('Using local copy of PubChem')
else:
    P2C = Prot2Comp('local', dbs=dbs) 
    print('Using PubChem API')

Using local copy of PubChem

In [11]:
times = {}

In [18]:
p2c_dat=pd.DataFrame()
p2c_fail=pd.DataFrame()
states = pd.DataFrame()

r=0
for h in tqdm(range(0,5)):
    
    protid=inputids['HGNC ID'].iloc[h]
    start = time.time()
    try:
        [comp_dat,state]=P2C.prot_interactions(input_id=protid,pChEMBL_thres=0,merge_stereoisomers=False,verbose=False)
        end = time.time()
        times[h] = end-start
        p2c_dat=pd.concat([p2c_dat,comp_dat])
        states = pd.concat([states, state])
        print(f'{h} done')
    except:
        # Collects failed inputids
        print(f'{h} failed')
        p2c_fail.loc[r,"failed_id"]=protid #Collects failed inputids
        r=r+1
    
    #Saves a file after a certain number of loops for insurance
    check=h/50 #automatically saves progress when on loop number set here
    if (check-int(check)==0)==True:
        filename=os.path.join(output_path, 'P2C_iter_'+str(h)+'.csv')
        p2c_dat.to_csv(filename,sep=',') 

# Save completed dataframe to file
filename=os.path.join(output_path, 'P2C.csv')
p2c_dat.to_csv(filename,sep=',',index=False)

 20%|██        | 1/5 [00:21<01:25, 21.29s/it]

0 done

 40%|████      | 2/5 [00:54<01:25, 28.48s/it]

1 done

 60%|██████    | 3/5 [01:26<01:00, 30.07s/it]

2 done

 80%|████████  | 4/5 [02:17<00:38, 38.28s/it]

3 done

100%|██████████| 5/5 [02:40<00:00, 32.05s/it]

4 done

In [19]:
p2c_dat

,input_id,entrez,gene_type,hgnc_symbol,description,inchi,inchikey,inchikey_fb,isomeric_smiles,iupac_name,...,src_count,pubchem,chembl,bindingdb,stitch,ctd,dtc,otp,drugcentral,drugbank
0,HGNC:4855,3067,protein_coding,HDC,histidine decarboxylase [Source:HGNC Symbol;Ac...,InChI=1S/C14H24N3O7P/c1-9-13(18)11(10(6-17-9)8...,FIXMYVJXXYQYGI-UHFFFAOYSA-N,FIXMYVJXXYQYGI,None,2-amino-6-[[3-hydroxy-2-methyl-5-(phosphonooxy...,...,1,0,0,0,1,0,0,0,0,0
1,HGNC:4855,3067,protein_coding,HDC,histidine decarboxylase [Source:HGNC Symbol;Ac...,InChI=1S/C9H12N2O3/c10-6-3-5(1-2-8(6)12)4-7(11...,POGSZHUEECCEAP-ZETCQYMHSA-N,POGSZHUEECCEAP,None,(2S)-2-amino-3-(3-amino-4-hydroxyphenyl)propan...,...,1,0,0,0,1,0,0,0,0,0
2,HGNC:4855,3067,protein_coding,HDC,histidine decarboxylase [Source:HGNC Symbol;Ac...,"InChI=1S/C8H12NO5P/c1-5-7(4-14-15(11,12)13)3-9...",RBCOYOYDYNXAFA-UHFFFAOYSA-N,RBCOYOYDYNXAFA,None,"(5-hydroxy-4,6-dimethyl-3-pyridinyl)methyl dih...",...,1,0,0,0,1,0,0,0,0,0
3,HGNC:4855,3067,protein_coding,HDC,histidine decarboxylase [Source:HGNC Symbol;Ac...,InChI=1S/C7H11N3O2/c1-12-7(11)6(8)2-5-3-9-4-10...,BXRMEWOQUXOLDH-LURJTMIESA-N,BXRMEWOQUXOLDH,None,methyl (2S)-2-amino-3-(1H-imidazol-5-yl)propan...,...,2,0,0,0,1,1,0,0,0,0
4,HGNC:4855,3067,protein_coding,HDC,histidine decarboxylase [Source:HGNC Symbol;Ac...,InChI=1S/Xe,FHNFHKCVQCLJFQ-UHFFFAOYSA-N,FHNFHKCVQCLJFQ,None,xenon,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901,HGNC:5211,3294,protein_coding,HSD17B2,hydroxysteroid 17-beta dehydrogenase 2 [Source...,InChI=1S/C20H26O3/c1-12(21)23-14-4-6-15-13(11-...,FHXBMXJMKMWVRG-SLHNCBLASA-N,FHXBMXJMKMWVRG,NaN,"[(8R,9S,13S,14S,17S)-17-hydroxy-13-methyl-6,7,...",...,1,0,0,0,0,0,0,0,0,1
902,HGNC:5211,3294,protein_coding,HSD17B2,hydroxysteroid 17-beta dehydrogenase 2 [Source...,InChI=1S/C25H28O3/c1-25-14-13-20-19-10-8-18(28...,UYIFTLBWAOGQBI-BZDYCCQFSA-N,UYIFTLBWAOGQBI,NaN,"[(8R,9S,13S,14S,17S)-17-hydroxy-13-methyl-6,7,...",...,1,0,0,0,0,0,0,0,0,1
903,HGNC:5211,3294,protein_coding,HSD17B2,hydroxysteroid 17-beta dehydrogenase 2 [Source...,InChI=1S/C26H36O3/c1-26-15-14-21-20-10-8-19(27...,UOACKFBJUYNSLK-XRKIENNPSA-N,UOACKFBJUYNSLK,NaN,"[(8R,9S,13S,14S,17S)-3-hydroxy-13-methyl-6,7,8...",...,1,0,0,0,0,0,0,0,0,1
904,HGNC:5211,3294,protein_coding,HSD17B2,hydroxysteroid 17-beta dehydrogenase 2 [Source...,InChI=1S/C32H48O4/c1-4-6-8-10-12-30(33)35-24-1...,OVAHZPTYWMWNKO-CAHAWPIUSA-N,OVAHZPTYWMWNKO,NaN,"[(8R,9S,13S,14S,17S)-3-heptanoyloxy-13-methyl-...",...,1,0,0,0,0,0,0,0,0,1
905,HGNC:5211,3294,protein_coding,HSD17B2,hydroxysteroid 17-beta dehydrogenase 2 [Source...,InChI=1S/C23H32O3/c1-3-4-5-22(25)26-21-11-10-2...,RSEPBGGWRJCQGY-RBRWEJTLSA-N,RSEPBGGWRJCQGY,NaN,"[(8R,9S,13S,14S,17S)-3-hydroxy-13-methyl-6,7,8...",...,1,0,0,0,0,0,0,0,0,1

In [20]:
states

,prot,pc,chembl,bdb,stitch,ctd,dtc,otp,dc,db
0,HGNC:4855,Filter reduced interactions to 0,Filter reduced interactions to 0,No interaction data,completed,completed,No interaction data,No interaction data in local OTP,No interaction data,completed
0,HGNC:29570,completed (local),completed,completed,completed,Filter reduced interactions to 0,No interaction data,No interaction data in local OTP,No interaction data,completed
0,HGNC:3531,completed (local),completed,completed,completed,Filter reduced interactions to 0,completed,No interaction data in local OTP,Filter reduced interactions to 0,completed
0,HGNC:7873,completed (local),completed,completed,completed,completed,completed,completed,completed,completed
0,HGNC:5211,Filter reduced interactions to 0,completed,completed,completed,completed,completed,No interaction data in local OTP,Filter reduced interactions to 0,completed

# Run Prot2Comp on Single Compound

## Prot2Compt2Comp with all Databases

### Test time required

In [23]:
protid='KLK1'

In [24]:
cProfile.run('P2C.prot_interactions(protid,merge_stereoisomers=False,verbose=False)')

         22823121 function calls (22469838 primitive calls) in 55.628 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       66    0.000    0.000    0.000    0.000 <frozen _collections_abc>:804(get)
       38    0.000    0.000    0.000    0.000 <frozen _collections_abc>:811(__contains__)
       19    0.000    0.000    0.000    0.000 <frozen _collections_abc>:819(keys)
       24    0.000    0.000    0.000    0.000 <frozen _collections_abc>:823(items)
       43    0.000    0.000    0.000    0.000 <frozen _collections_abc>:845(__init__)
        6    0.000    0.000    0.000    0.000 <frozen _collections_abc>:848(__len__)
     2432    0.001    0.000    0.003    0.000 <frozen _collections_abc>:868(__iter__)
      120    0.000    0.000    0.000    0.000 <frozen _collections_abc>:892(__iter__)
       54    0.000    0.000    0.001    0.000 <frozen _collections_abc>:974(update)
    62694    0.016    0.000    0.042    0.000 <frozen abc>:117(__instancecheck__)
        4    0.000    0.000    0.000    0.000 <frozen abc>:121(__subclasscheck__)
        2    0.000    0.000    0.000    0.000 <frozen codecs>:186(__init__)
        2    0.000    0.000    0.000    0.000 <frozen codecs>:260(__init__)
       63    0.000    0.000    0.000    0.000 <frozen codecs>:276(reset)
       12    0.000    0.000    0.001    0.000 <frozen genericpath>:16(exists)
    21271    0.021    0.000    0.029    0.000 <frozen importlib._bootstrap>:1390(_handle_fromlist)
      131    0.000    0.000    0.000    0.000 <frozen os>:709(__getitem__)
     2432    0.001    0.000    0.002    0.000 <frozen os>:732(__iter__)
      131    0.000    0.000    0.000    0.000 <frozen os>:791(encode)
     2494    0.001    0.000    0.001    0.000 <frozen os>:795(decode)
       12    0.000    0.000    0.000    0.000 <frozen posixpath>:256(expanduser)
       12    0.000    0.000    0.000    0.000 <frozen posixpath>:41(_get_sep)
       85    0.000    0.000    0.000    0.000 <string>:1(<lambda>)
        2    0.000    0.000    0.000    0.000 <string>:2(__init__)
        1    0.000    0.000    0.538    0.538 BindingDB.py:204(compounds)
        1    0.000    0.000    0.007    0.007 BindingDB.py:21(_filter_database)
        1    0.000    0.000    0.024    0.024 BindingDB.py:51(_compute_pchembl)
      252    0.000    0.000    0.000    0.000 BindingDB.py:75(<lambda>)
        2    0.010    0.005   10.884    5.442 BiomartServer.py:22(search)
        1    0.000    0.000    0.327    0.327 CTD.py:128(compounds)
        1    0.000    0.000    0.004    0.004 CTD.py:19(_filter_database)
        1    0.000    0.000    1.097    1.097 ChEMBL.py:185(compounds)
        1    0.000    0.000    0.008    0.008 ChEMBL.py:37(_filter_database)
      192    0.000    0.000    0.000    0.000 ChEMBL.py:53(<lambda>)
        1    0.000    0.000    1.031    1.031 DTC.py:200(compounds)
        1    0.000    0.000    0.005    0.005 DTC.py:26(_filter_database)
        1    0.001    0.001    0.132    0.132 DTC.py:312(_standard_converter)
        1    0.000    0.000    0.142    0.142 DTC.py:52(_standardize_database)
        6    0.001    0.000    2.156    0.359 Database.py:32(_pubchem_search_cid)
        1    0.000    0.000    0.242    0.242 DrugBank.py:133(compounds)
        1    0.000    0.000    0.010    0.010 DrugCentral.py:143(compounds)
        1    0.000    0.000    0.003    0.003 DrugCentral.py:21(_filter_database)
        1    0.000    0.000    0.002    0.002 DrugCentral.py:36(_compute_pchembl)
     6442    0.001    0.000    0.001    0.000 ElementPath.py:165(select)
  520/468    0.000    0.000    0.000    0.000 ElementPath.py:173(select)
       32    0.000    0.000    0.000    0.000 ElementPath.py:179(select)
       26    0.002    0.000    0.004    0.000 ElementPath.py:260(select)
       16    0.000    0.000    0.000    0.000 ElementPath.py:352(__init__)
       16    0.000    0.000    0.000    0.000 ElementPath.py:360(iterfind)
       16    0.000    0.000    0.004    0.000 ElementPath.py:410(findall)
       29    0.000    0.000    0.000    0.000 ElementTree.py:1024(_escape_attrib)
        2    0.000    0.000    0.001    0.000 ElementTree.py:1067(tostring)
        2    0.015    0.007    0.156    0.078 ElementTree.py:1322(XML)
        2    0.000    0.000    0.000    0.000 ElementTree.py:525(__init__)
        2    0.000    0.000    0.000    0.000 ElementTree.py:679(write)
        4    0.000    0.000    0.000    0.000 ElementTree.py:739(_get_writer)
        2    0.000    0.000    0.000    0.000 ElementTree.py:789(_namespaces)
       26    0.000    0.000    0.000    0.000 ElementTree.py:800(add_qname)
     15/2    0.000    0.000    0.000    0.000 ElementTree.py:850(_serialize_xml)
        7    0.001    0.000    2.135    0.305 LocalManager.py:6(retrieve_raw_data)
        1    0.000    0.000    0.005    0.005 OTP.py:258(compounds)
        1    0.000    0.000    0.002    0.002 OTP.py:485(_query_local_moa_by_target)
     2133    0.054    0.000    6.573    0.003 Pipeline.py:117(_aggregate_pchembl)
        1    0.000    0.000    0.000    0.000 Prot2Comp.py:10(_update_args)
        4    0.000    0.000    0.001    0.000 Prot2Comp.py:100(<lambda>)
        1    0.554    0.554   18.999   18.999 Prot2Comp.py:115(_postprocess_databases)
     2565    0.001    0.000    0.005    0.000 Prot2Comp.py:122(<lambda>)
        1    0.003    0.003   51.259   51.259 Prot2Comp.py:49(prot_interactions_select)
        1    4.950    4.950   25.196   25.196 PubChem.py:297(compounds)
        6    0.000    0.000    0.000    0.000 PubChemServer.py:13(get_columns)
        7    0.000    0.000    3.551    0.507 PubChemServer.py:16(get_compounds)
     2374    0.001    0.000    0.001    0.000 PubChemServer.py:63(get_inchikey_first_block)
        1    0.000    0.000    0.386    0.386 Stitch.py:147(compounds)
       26    0.000    0.000    0.000    0.000 __init__.py:1517(debug)
       63    0.000    0.000    0.000    0.000 __init__.py:179(sub)
       26    0.000    0.000    0.000    0.000 __init__.py:1790(isEnabledFor)
     2183    0.002    0.000    0.016    0.000 __init__.py:226(compile)
     2246    0.010    0.000    0.014    0.000 __init__.py:280(_compile)
        7    0.000    0.000    0.009    0.001 __init__.py:299(loads)
   370680    0.087    0.000    0.087    0.000 __init__.py:34(using_copy_on_write)
   175162    0.050    0.000    0.050    0.000 __init__.py:42(warn_copy_on_write)
    38928    0.018    0.000    0.140    0.000 __init__.py:535(_check_cacher)
     6802    0.004    0.000    0.004    0.000 __init__.py:55(using_string_dtype)
       42    0.000    0.000    0.001    0.000 _asarray.py:27(require)
        1    0.000    0.000    0.002    0.002 _base.py:337(_invoke_callbacks)
        1    0.000    0.000    0.002    0.002 _base.py:537(set_result)
        6    0.000    0.000    0.000    0.000 _collections.py:141(__init__)
       84    0.000    0.000    0.000    0.000 _collections.py:156(__getitem__)
       66    0.000    0.000    0.000    0.000 _collections.py:187(__iter__)
       60    0.000    0.000    0.000    0.000 _collections.py:215(add)
        6    0.000    0.000    0.000    0.000 _collections.py:231(extend)
       18    0.000    0.000    0.000    0.000 _collections.py:47(__init__)
        6    0.000    0.000    0.000    0.000 _collections.py:54(__getitem__)
        6    0.000    0.000    0.000    0.000 _collections.py:61(__setitem__)
       18    0.000    0.000    0.000    0.000 _collections.py:92(clear)
        2    0.000    0.000    0.000    0.000 _decorators.py:325(wrapper)
    24908    0.009    0.000    0.009    0.000 _dtype.py:24(_kind_name)
    24908    0.013    0.000    0.024    0.000 _dtype.py:330(_name_includes_bit_suffix)
        2    0.000    0.000    0.000    0.000 _dtype.py:34(__str__)
    24908    0.062    0.000    0.104    0.000 _dtype.py:346(_name_get)
       30    0.000    0.000    0.000    0.000 _internal_utils.py:25(to_native_string)
        6    0.000    0.000    0.000    0.000 _internal_utils.py:38(unicode_is_ascii)
     1061    0.007    0.000    0.023    0.000 _methods.py:101(_mean)
     1061    0.032    0.000    0.058    0.000 _methods.py:135(_var)
     1061    0.005    0.000    0.063    0.000 _methods.py:204(_std)
     2269    0.001    0.000    0.010    0.000 _methods.py:39(_amax)
     2152    0.001    0.000    0.006    0.000 _methods.py:43(_amin)
       19    0.000    0.000    0.000    0.000 _methods.py:47(_sum)
     4690    0.003    0.000    0.020    0.000 _methods.py:55(_any)
      114    0.000    0.000    0.002    0.000 _methods.py:61(_all)
     2122    0.009    0.000    0.010    0.000 _methods.py:67(_count_reduce_items)
       10    0.000    0.000    0.001    0.000 _monitor.py:47(get_instances)
      138    0.000    0.000    0.001    0.000 _policybase.py:281(_sanitize_header)
      186    0.001    0.000    0.001    0.000 _policybase.py:293(header_source_parse)
      138    0.000    0.000    0.001    0.000 _policybase.py:311(header_fetch_parse)
     2128    0.003    0.000    0.004    0.000 _ufunc_config.py:132(geterr)
     2128    0.006    0.000    0.013    0.000 _ufunc_config.py:33(seterr)
     1064    0.000    0.000    0.000    0.000 _ufunc_config.py:426(__init__)
     1064    0.002    0.000    0.010    0.000 _ufunc_config.py:430(__enter__)
     1064    0.002    0.000    0.007    0.000 _ufunc_config.py:435(__exit__)
     2122    0.001    0.000    0.004    0.000 _ufunc_config.py:452(_no_nep50_warning)
       22    0.000    0.000    0.000    0.000 _validators.py:128(_check_for_invalid_keys)
       22    0.000    0.000    0.000    0.000 _validators.py:141(validate_kwargs)
     4458    0.002    0.000    0.002    0.000 _validators.py:226(validate_bool_kwarg)
     3836    0.001    0.000    0.001    0.000 _validators.py:450(check_dtype_backend)
       22    0.000    0.000    0.000    0.000 _validators.py:49(_check_for_default_values)
       10    0.000    0.000    0.001    0.000 _weakrefset.py:120(update)
       20    0.000    0.000    0.000    0.000 _weakrefset.py:17(__init__)
       20    0.000    0.000    0.000    0.000 _weakrefset.py:21(__enter__)
       20    0.000    0.000    0.000    0.000 _weakrefset.py:27(__exit__)
       10    0.000    0.000    0.001    0.000 _weakrefset.py:37(__init__)
       20    0.000    0.000    0.000    0.000 _weakrefset.py:53(_commit_removals)
       20    0.000    0.000    0.001    0.000 _weakrefset.py:63(__iter__)
       10    0.000    0.000    0.001    0.000 _weakrefset.py:95(copy)
        1    0.000    0.000    0.000    0.000 accessor.py:1205(contains)
        6    0.000    0.000    0.011    0.002 accessor.py:132(wrapper)
        4    0.000    0.000    0.009    0.002 accessor.py:1432(replace)
        6    0.000    0.000    0.001    0.000 accessor.py:191(__init__)
        6    0.000    0.000    0.000    0.000 accessor.py:210(_validate)
        1    0.000    0.000    0.002    0.002 accessor.py:2154(lstrip)
        6    0.000    0.000    0.001    0.000 accessor.py:220(__get__)
        6    0.000    0.000    0.001    0.000 accessor.py:258(_wrap_result)
       12    0.000    0.000    0.000    0.000 adapters.py:116(__init__)
       12    0.000    0.000    0.000    0.000 adapters.py:178(__init__)
       12    0.000    0.000    0.000    0.000 adapters.py:216(init_poolmanager)
        6    0.000    0.000    0.000    0.000 adapters.py:242(proxy_manager_for)
        6    0.000    0.000    0.000    0.000 adapters.py:280(cert_verify)
        6    0.000    0.000    0.001    0.000 adapters.py:336(build_response)
        6    0.000    0.000    0.000    0.000 adapters.py:373(build_connection_pool_key_attributes)
        6    0.000    0.000    0.003    0.000 adapters.py:423(get_connection_with_tls_context)
       12    0.000    0.000    0.000    0.000 adapters.py:513(close)
        6    0.000    0.000    0.000    0.000 adapters.py:523(request_url)
        6    0.000    0.000    0.000    0.000 adapters.py:555(add_headers)
        6    0.000    0.000    0.000    0.000 adapters.py:569(proxy_headers)
        6    0.000    0.000   10.388    1.731 adapters.py:590(send)
        6    0.000    0.000    0.000    0.000 adapters.py:76(_urllib3_request_context)
    23556    0.053    0.000    0.214    0.000 algorithms.py:106(_ensure_data)
       73    0.000    0.000    0.001    0.000 algorithms.py:1131(take)
       14    0.002    0.000    0.030    0.002 algorithms.py:1667(map_array)
    23622    0.026    0.000    0.084    0.000 algorithms.py:184(_reconstruct_data)
    23614    0.016    0.000    0.104    0.000 algorithms.py:217(_ensure_arraylike)
    23546    0.027    0.000    0.481    0.000 algorithms.py:262(_get_hashtable_algo)
    23546    0.142    0.000    0.240    0.000 algorithms.py:280(_check_object_for_strings)
    23470    0.023    0.000    1.008    0.000 algorithms.py:307(unique)
    23470    0.311    0.000    0.985    0.000 algorithms.py:427(unique_with_mask)
       34    0.001    0.000    0.003    0.000 algorithms.py:457(isin)
       76    0.003    0.000    0.005    0.000 algorithms.py:548(factorize_array)
       76    0.000    0.000    0.007    0.000 algorithms.py:610(factorize)
       10    0.000    0.000    0.000    0.000 algorithms.py:994(duplicated)
     1084    0.015    0.000    0.027    0.000 api.py:106(_get_distinct_objs)
     1084    0.005    0.000    0.112    0.000 api.py:120(_get_combined_index)
        6    0.000    0.000   10.399    1.733 api.py:14(request)
     1077    0.009    0.000    0.079    0.000 api.py:202(union_indexes)
        1    0.000    0.000    0.001    0.001 api.py:231(_unique_indices)
        3    0.000    0.000    0.000    0.000 api.py:244(<genexpr>)
     1076    0.006    0.000    0.010    0.000 api.py:265(_find_common_index_dtype)
    18236    0.007    0.000    0.021    0.000 api.py:318(<genexpr>)
     1077    0.004    0.000    0.005    0.000 api.py:330(_sanitize_and_check)
       96    0.000    0.000    0.001    0.000 api.py:386(default_index)
        6    0.000    0.000   10.399    1.733 api.py:62(get)
     1084    0.007    0.000    0.132    0.000 api.py:72(get_objs_combined_axis)
        3    0.000    0.000    0.006    0.002 apply.py:1061(apply_standard)
        3    0.000    0.000    0.005    0.002 apply.py:1070(apply_series_generator)
        3    0.000    0.000    0.001    0.000 apply.py:1102(wrap_results)
        3    0.000    0.000    0.000    0.000 apply.py:1137(series_generator)
       15    0.000    0.000    0.000    0.000 apply.py:1139(<genexpr>)
        3    0.000    0.000    0.000    0.000 apply.py:1185(result_index)
        4    0.000    0.000    0.000    0.000 apply.py:1189(result_columns)
        2    0.000    0.000    0.001    0.000 apply.py:1193(wrap_results_for_axis)
        2    0.000    0.000    0.000    0.000 apply.py:1204(<genexpr>)
       10    0.000    0.000    0.000    0.000 apply.py:121(__init__)
        7    0.000    0.000    0.000    0.000 apply.py:1372(__init__)
        7    0.000    0.000    0.028    0.004 apply.py:1404(apply)
        1    0.000    0.000    0.000    0.000 apply.py:1449(apply_empty_result)
        6    0.000    0.000    0.028    0.005 apply.py:1477(apply_standard)
     1449    0.001    0.000    0.021    0.000 apply.py:1490(curried)
        3    0.000    0.000    0.000    0.000 apply.py:1638(reconstruct_func)
        4    0.000    0.000    0.000    0.000 apply.py:717(index)
        3    0.000    0.000    0.000    0.000 apply.py:773(__init__)
        3    0.000    0.000    0.000    0.000 apply.py:82(frame_apply)
        4    0.000    0.000    0.000    0.000 apply.py:852(res_columns)
        9    0.000    0.000    0.000    0.000 apply.py:856(columns)
        3    0.000    0.000    0.006    0.002 apply.py:864(apply)
     2149    0.901    0.000    0.911    0.000 array_ops.py:113(comp_method_OBJECT_ARRAY)
       14    0.000    0.000    0.002    0.000 array_ops.py:189(_na_arithmetic_op)
        2    0.000    0.000    0.000    0.000 array_ops.py:240(arithmetic_op)
     2162    0.015    0.000    1.593    0.001 array_ops.py:288(comparison_op)
       20    0.000    0.000    0.000    0.000 array_ops.py:352(na_logical_op)
       20    0.000    0.000    0.001    0.000 array_ops.py:393(logical_op)
       40    0.000    0.000    0.000    0.000 array_ops.py:410(fill_bool)
        2    0.000    0.000    0.000    0.000 array_ops.py:507(maybe_prepare_scalar_for_op)
        2    0.000    0.000    0.000    0.000 array_ops.py:594(_bool_arith_check)
        2    0.000    0.000    0.001    0.000 arraylike.py:208(__truediv__)
        2    0.000    0.000    0.000    0.000 arraylike.py:253(array_ufunc)
        4    0.000    0.000    0.000    0.000 arraylike.py:300(<genexpr>)
        2    0.000    0.000    0.000    0.000 arraylike.py:338(reconstruct)
        2    0.000    0.000    0.000    0.000 arraylike.py:345(_reconstruct)
     2151    0.004    0.000    2.758    0.001 arraylike.py:38(__eq__)
        4    0.000    0.000    0.000    0.000 arraylike.py:398(<genexpr>)
        2    0.000    0.000    0.000    0.000 arraylike.py:418(_standardize_out_kwarg)
        2    0.000    0.000    0.000    0.000 arraylike.py:42(__ne__)
        2    0.000    0.000    0.000    0.000 arraylike.py:46(__lt__)
        7    0.000    0.000    0.001    0.000 arraylike.py:54(__gt__)
       18    0.000    0.000    0.003    0.000 arraylike.py:68(__and__)
        2    0.000    0.000    0.000    0.000 arraylike.py:76(__or__)
     2195    0.002    0.000    0.023    0.000 astype.py:157(astype_array)
     2193    0.007    0.000    0.122    0.000 astype.py:191(astype_array_safe)
        1    0.000    0.000    0.000    0.000 astype.py:249(astype_is_view)
       11    0.000    0.000    0.000    0.000 astype.py:56(_astype_nansafe)
        1    0.000    0.000    0.000    0.000 asyncio.py:200(_handle_events)
        1    0.000    0.000    0.000    0.000 asyncio.py:225(add_callback)
     6340    0.001    0.000    0.001    0.000 attribute.py:2(__init__)
       14    0.000    0.000    0.000    0.000 attribute_page.py:2(__init__)
     6340    0.002    0.000    0.002    0.000 attribute_page.py:9(add)
        5    0.000    0.000    0.000    0.000 attrsettr.py:42(__getattr__)
        5    0.000    0.000    0.000    0.000 attrsettr.py:65(_get_attr_opt)
    17344    0.018    0.000    0.093    0.000 base.py:1017(view)
    23470    0.037    0.000    1.072    0.000 base.py:1023(unique)
        2    0.000    0.000    0.000    0.000 base.py:1052(astype)
       73    0.001    0.000    0.002    0.000 base.py:1153(take)
     2255    0.001    0.000    0.001    0.000 base.py:1183(_maybe_disallow_fill)
        5    0.000    0.000    0.000    0.000 base.py:123(_reset_cache)
        6    0.000    0.000    0.000    0.000 base.py:1257(copy)
       10    0.000    0.000    0.000    0.000 base.py:1373(_duplicated)
        2    0.000    0.000    0.000    0.000 base.py:1380(_arith_method)
        6    0.000    0.000    0.000    0.000 base.py:152(na_value)
        6    0.000    0.000    0.000    0.000 base.py:160(_freeze)
       60    0.000    0.000    0.000    0.000 base.py:167(__setattr__)
    61458    0.011    0.000    0.011    0.000 base.py:1678(name)
       11    0.000    0.000    0.000    0.000 base.py:1704(_validate_names)
       22    0.000    0.000    0.001    0.000 base.py:176(isna)
    18283    0.009    0.000    0.011    0.000 base.py:1772(_get_names)
        2    0.000    0.000    0.000    0.000 base.py:1775(_set_names)
        2    0.000    0.000    0.000    0.000 base.py:1816(set_names)
        2    0.000    0.000    0.000    0.000 base.py:1929(rename)
       27    0.000    0.000    0.000    0.000 base.py:1986(nlevels)
       10    0.000    0.000    0.000    0.000 base.py:2236(is_monotonic_increasing)
     1140    0.008    0.000    0.038    0.000 base.py:2320(is_unique)
    47652    0.040    0.000    0.048    0.000 base.py:238(construct_from_string)
        1    0.000    0.000    0.000    0.000 base.py:267(replace_list)
     1191    0.015    0.000    0.020    0.000 base.py:2751(inferred_type)

### Run pipeline

In [25]:
protid='Q12809'

In [26]:
if 'pubchem_files' in locals():
    P2C = Prot2Comp('local', dbs=dbs, pubchem_files=pubchem_files)
    print('Using local copy of PubChem')
else:
    P2C = Prot2Comp('local', dbs=dbs) 
    print('Using PubChem API')

Using local copy of PubChem

In [27]:
[comp_dat,states]=P2C.prot_interactions(input_id=protid,pChEMBL_thres=0,merge_stereoisomers=False,verbose=False)

In [28]:
comp_dat

,input_id,entrez,gene_type,hgnc_symbol,description,inchi,inchikey,inchikey_fb,isomeric_smiles,iupac_name,...,src_count,pubchem,chembl,bindingdb,stitch,ctd,dtc,otp,drugcentral,drugbank
0,Q12809,3757,protein_coding,KCNH2,potassium voltage-gated channel subfamily H me...,InChI=1S/C17H25NO4/c1-20-13-11-15(21-2)17(16(1...,OWYLAEYXIQKAOL-UHFFFAOYSA-N,OWYLAEYXIQKAOL,None,None,...,1,1,0,0,0,0,0,0,0,0
1,Q12809,3757,protein_coding,KCNH2,potassium voltage-gated channel subfamily H me...,InChI=1S/C18H30N2O2/c1-3-5-12-20(13-6-4-2)14-7...,HQFWVSGBVLEQGA-UHFFFAOYSA-N,HQFWVSGBVLEQGA,None,None,...,1,1,0,0,0,0,0,0,0,0
2,Q12809,3757,protein_coding,KCNH2,potassium voltage-gated channel subfamily H me...,"InChI=1S/C23H27N/c1-23(2,3)21-14-12-18(13-15-2...",ABJKWBDEJIDSJZ-UHFFFAOYSA-N,ABJKWBDEJIDSJZ,None,None,...,1,1,0,0,0,0,0,0,0,0
3,Q12809,3757,protein_coding,KCNH2,potassium voltage-gated channel subfamily H me...,InChI=1S/C20H21N/c1-21(2)15-7-12-20-18-10-5-3-...,JURKNVYFZMSNLP-UHFFFAOYSA-N,JURKNVYFZMSNLP,None,None,...,1,1,0,0,0,0,0,0,0,0
4,Q12809,3757,protein_coding,KCNH2,potassium voltage-gated channel subfamily H me...,InChI=1S/C17H21NO/c1-18(2)13-14-19-17(15-9-5-3...,ZZVUWRFHKOJYTH-UHFFFAOYSA-N,ZZVUWRFHKOJYTH,None,None,...,3,1,1,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17318,Q12809,3757,protein_coding,KCNH2,potassium voltage-gated channel subfamily H me...,InChI=1S/C5H7N3.H3O4P/c6-4-1-2-8-3-5(4)7;1-5(2...,KAICRBBQCRKMPO-UHFFFAOYSA-N,KAICRBBQCRKMPO,None,"phosphoric acid;pyridine-3,4-diamine",...,1,0,0,0,0,0,0,1,0,0
17319,Q12809,3757,protein_coding,KCNH2,potassium voltage-gated channel subfamily H me...,"InChI=1S/C5H7N3/c6-4-1-2-8-3-5(4)7/h1-3H,7H2,(...",OYTKINVCDFNREN-UHFFFAOYSA-N,OYTKINVCDFNREN,None,"pyridine-3,4-diamine",...,1,0,0,0,0,0,0,1,0,0
17320,Q12809,3757,protein_coding,KCNH2,potassium voltage-gated channel subfamily H me...,InChI=1S/K.NO3/c;2-1(3)4/q+1;-1,FGIUAXJPYTZDNR-UHFFFAOYSA-N,FGIUAXJPYTZDNR,NaN,potassium nitrate,...,1,0,0,0,0,0,0,0,0,1
17321,Q12809,3757,protein_coding,KCNH2,potassium voltage-gated channel subfamily H me...,InChI=1S/C20H31NO3/c1-3-21(4-2)14-15-23-16-17-...,CFJMRBQWBDQYMK-UHFFFAOYSA-N,CFJMRBQWBDQYMK,NaN,2-[2-(diethylamino)ethoxy]ethyl 1-phenylcyclop...,...,1,0,0,0,0,0,0,0,0,1
17322,Q12809,3757,protein_coding,KCNH2,potassium voltage-gated channel subfamily H me...,InChI=1S/C22H17F2N5OS/c1-14(21-28-20(10-31-21)...,DDFOUSQFMYRUQK-RCDICMHDSA-N,DDFOUSQFMYRUQK,NaN,"4-[2-[(2R,3R)-3-(2,5-difluorophenyl)-3-hydroxy...",...,1,0,0,0,0,0,0,0,0,1

In [29]:
states

,prot,pc,chembl,bdb,stitch,ctd,dtc,otp,dc,db
0,Q12809,completed (local),completed,completed,No interaction data,completed,completed,completed,completed,completed

### Prot2Compt with select Databases

In [30]:
protid='KLK1'

In [31]:
if 'pubchem_files' in locals():
    P2C = Prot2Comp('local', dbs=dbs, pubchem_files=pubchem_files)
    print('Using local copy of PubChem')
else:
    P2C = Prot2Comp('local', dbs=dbs) 
    print('Using PubChem API')

Using local copy of PubChem

In [32]:
#The second argument is a string listing the databases needed.
#Underscore is required to separate the databases.
[comp_dat,states]=P2C.prot_interactions_select(protid,'ctd_bdb',merge_stereoisomers=False,verbose=False)

In [33]:
comp_dat

,input_id,entrez,gene_type,hgnc_symbol,description,inchi,inchikey,inchikey_fb,isomeric_smiles,iupac_name,...,src_count,pubchem,chembl,bindingdb,stitch,ctd,dtc,otp,drugcentral,drugbank
0,KLK1,3816,protein_coding,KLK1,kallikrein 1 [Source:HGNC Symbol;Acc:HGNC:6357],InChI=1S/C37H50BN5O6S/c1-36(2)26-21-29(36)37(3...,KAUYBZJFBAONCO-LTNQQUILSA-N,KAUYBZJFBAONCO,None,benzyl N-[(2S)-1-[(2S)-2-[[5-hydrazinyl-5-sulf...,...,1,0,0,1,0,0,0,0,0,0
1,KLK1,3816,protein_coding,KLK1,kallikrein 1 [Source:HGNC Symbol;Acc:HGNC:6357],InChI=1S/C18H16N2O2/c19-11-12-5-7-15(8-6-12)20...,VRZLGSXKZZLNLO-UHFFFAOYSA-N,VRZLGSXKZZLNLO,None,N-[4-(aminomethyl)phenyl]-3-hydroxynaphthalene...,...,1,0,0,1,0,0,0,0,0,0
2,KLK1,3816,protein_coding,KLK1,kallikrein 1 [Source:HGNC Symbol;Acc:HGNC:6357],InChI=1S/C15H13ClN4O3S/c16-12-4-3-9(24-12)7-17...,HYFHMVXNRDCJBE-UHFFFAOYSA-N,HYFHMVXNRDCJBE,None,2-[3-[3-[(5-chlorothiophen-2-yl)methylamino]-1...,...,1,0,0,1,0,0,0,0,0,0
3,KLK1,3816,protein_coding,KLK1,kallikrein 1 [Source:HGNC Symbol;Acc:HGNC:6357],InChI=1S/C21H17ClN4O3S/c1-29-17-7-3-2-5-15(17)...,QTLZDCOXZLGEHT-UHFFFAOYSA-N,QTLZDCOXZLGEHT,None,3-[5-[(5-chlorothiophen-2-yl)methylamino]-1-(2...,...,1,0,0,1,0,0,0,0,0,0
4,KLK1,3816,protein_coding,KLK1,kallikrein 1 [Source:HGNC Symbol;Acc:HGNC:6357],InChI=1S/C21H23N3O/c1-15-11-20(24-19(15)12-16-...,QVAQGAPHNCKJJL-UHFFFAOYSA-N,QVAQGAPHNCKJJL,None,N-[[4-(aminomethyl)phenyl]methyl]-2-benzyl-3-m...,...,1,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,KLK1,3816,protein_coding,KLK1,kallikrein 1 [Source:HGNC Symbol;Acc:HGNC:6357],InChI=1S/C13H10N2O4/c16-10-6-5-9(11(17)14-10)1...,UEJJHQNACJXSKW-UHFFFAOYSA-N,UEJJHQNACJXSKW,None,"2-(2,6-dioxopiperidin-3-yl)isoindole-1,3-dione",...,1,0,0,0,0,1,0,0,0,0
105,KLK1,3816,protein_coding,KLK1,kallikrein 1 [Source:HGNC Symbol;Acc:HGNC:6357],InChI=1S/2O.Ti,GWEVSGVZZGPLCZ-UHFFFAOYSA-N,GWEVSGVZZGPLCZ,None,dioxotitanium,...,1,0,0,0,0,1,0,0,0,0
106,KLK1,3816,protein_coding,KLK1,kallikrein 1 [Source:HGNC Symbol;Acc:HGNC:6357],InChI=1S/C20H28O2/c1-15(8-6-9-16(2)14-19(21)22...,SHGAZHPCJJPHSC-YCNIQYBTSA-N,SHGAZHPCJJPHSC,None,"(2E,4E,6E,8E)-3,7-dimethyl-9-(2,6,6-trimethylc...",...,1,0,0,0,0,1,0,0,0,0
107,KLK1,3816,protein_coding,KLK1,kallikrein 1 [Source:HGNC Symbol;Acc:HGNC:6357],InChI=1S/C2HCl3/c3-1-2(4)5/h1H,XSTXAVWGXDQKEL-UHFFFAOYSA-N,XSTXAVWGXDQKEL,None,"1,1,2-trichloroethene",...,1,0,0,0,0,1,0,0,0,0
108,KLK1,3816,protein_coding,KLK1,kallikrein 1 [Source:HGNC Symbol;Acc:HGNC:6357],InChI=1S/C12H9Cl2NO3/c1-3-12(2)10(16)15(11(17)...,FSCWZHGZWWDELK-UHFFFAOYSA-N,FSCWZHGZWWDELK,None,"3-(3,5-dichlorophenyl)-5-ethenyl-5-methyl-1,3-...",...,1,0,0,0,0,1,0,0,0,0

In [34]:
states

,prot,pc,chembl,bdb,stitch,ctd,dtc,otp,dc,db
0,KLK1,Did not run pc,Did not run chembl,completed,Did not run stitch,completed,Did not run dtc,Did not run otp,Did not run dc,Did not run db

# Run each step/database separately (for troubleshooting)

In [39]:
from cpiextract.databases import *
from cpiextract.utils import protein_identifiers
input_id='KLK1'
protids=protein_identifiers(input_id)

### Run PubChem only

In [35]:
#Local PubChem will improve speed. Only run if you have the resources for a local pubchem.
data_path='data/Databases/'
file_path=os.path.join(data_path,'pubchem.duckdb')

In [40]:
if 'file_path' in locals():
    pubchem=PubChem(bioact_file=file_path)
    print('Using local copy of PubChem')
else:
    pubchem=PubChem()
    print('Using PubChem API')

[pc_dat,pc_state,pc_raw]=pubchem.compounds(protids,pChEMBL_thres=0,merge_stereoisomers=False,verbose=False)

Using local copy of PubChem

In [41]:
pc_dat

,inchi,inchikey,isomeric_smiles,iupac_name,datasource,pchembl_value
0,InChI=1S/C19H17N5O2/c20-17(21)14-2-1-13-10-16(...,MQQNFDZXWVTQEH-UHFFFAOYSA-N,None,(6-carbamimidoylnaphthalen-2-yl) 4-(diaminomet...,PubChem,6.187087
1,InChI=1S/C14H8INO2/c15-11-7-3-1-5-9(11)13-16-1...,VEBIXPCJYGGBAF-UHFFFAOYSA-N,None,"2-(2-iodophenyl)-3,1-benzoxazin-4-one",PubChem,5.004804
2,InChI=1S/C38H52BN3O6/c1-5-6-9-20-33(39-47-32-2...,MUPHEXMZSXMJJT-DTNILZMJSA-N,None,benzyl N-[(2S)-1-oxo-3-phenyl-1-[(2S)-2-[1-[(2...,PubChem,6.920819
3,InChI=1S/C44H56BN3O6/c1-5-6-10-25-37(45-53-36-...,QPBFLOWZPFHTHE-ADVKVLRRSA-N,None,"benzyl N-[(2S)-1-oxo-3,3-diphenyl-1-[(2S)-2-[1...",PubChem,6.795880
4,"InChI=1S/C38H52BN3O6/c1-7-36(2,3)34(39-47-31-2...",GOBXSXIHPUGHDS-MDFDAHAVSA-N,None,"benzyl N-[(2S)-1-[(2S)-2-[[2,2-dimethyl-1-[(2S...",PubChem,8.022276
...,...,...,...,...,...,...
998,InChI=1S/C20H22F3N7O/c1-13(2)31-18-9-15(5-6-24...,LFUVXXPUSUZVRA-UHFFFAOYSA-N,None,"2-propan-2-yloxy-N-[[6-[3-(trifluoromethyl)-6,...",PubChem,8.522879
999,InChI=1S/C20H15ClF3N9/c1-31(14-6-11(8-25)27-18...,KKTSRKPADJIMFN-UHFFFAOYSA-N,None,"2-chloro-4-[methyl-[6-[3-(trifluoromethyl)-6,8...",PubChem,8.522879
1000,InChI=1S/C20H18ClF3N8/c1-11-6-14(13-7-15(21)28...,FYZGILZDVGOGLF-UHFFFAOYSA-N,None,2-chloro-6-methyl-N-[[6-[3-(trifluoromethyl)-6...,PubChem,8.522879
1001,"InChI=1S/C22H18F6N8/c23-21(24,25)15-8-12(9-31-...",GMEVUQTYPVXYRL-UHFFFAOYSA-N,None,5-N-[[5-(trifluoromethyl)-6-[3-(trifluoromethy...,PubChem,5.698970
1002,InChI=1S/C20H32ClN5O/c1-26-9-6-14(7-10-26)13-2...,FQWBZDJIQILLMU-UHFFFAOYSA-N,None,3-chloro-N-[[2-[(1-methylpiperidin-4-yl)methox...,PubChem,5.698970

In [42]:
pc_state

'completed (API)'

### Run ChEMBL only

In [43]:
file_path=os.path.join(data_path, 'ChEMBL_Dec2025.csv')
chembl_data=pd.read_csv(file_path,sep=',',low_memory=False,index_col=0)

In [45]:
chembl = ChEMBL(database=chembl_data)
[chembl_dat, state, chembl_raw]=chembl.compounds(protids,pChEMBL_thres=0,merge_stereoisomers=False)

In [46]:
chembl_dat

,CID,SMILES,inchi,inchikey,iupac_name,id,pchembl_value,target_chembl_id,datasource,notes
0,9826716,C1=CC=C(C(=C1)C2=CC=C(C=C2)C(=O)NC3=CC=CC=C3OC...,InChI=1S/C26H22N4O4S/c27-25(28)19-6-5-7-20(16-...,DUVLBBOBLCROSD-UHFFFAOYSA-N,N-[2-(3-carbamimidoylphenoxy)phenyl]-4-(2-sulf...,CHEMBL297835,6.60,CHEMBL2319,ChEMBL,NaN
1,14488970,CC(C)C[C@@H](C(=O)N[C@@H](C(C)C)C(=O)N[C@@H](C...,InChI=1S/C25H40N4O5/c1-17(2)14-21(28-25(33)34-...,YFFIKGWBJWHXNP-FKBYEOEOSA-N,benzyl N-[(2S)-1-[[(2S)-1-[[(2S)-6-amino-1-oxo...,CHEMBL2371625,4.83,CHEMBL2319,ChEMBL,NaN
2,44285312,B1(O[C@@H]2CC3CC([C@@]2(O1)C)C3(C)C)C(CC4=CC=C...,InChI=1S/C46H52BN3O6/c1-45(2)35-28-37(45)46(3)...,SAHIWIHDGKJMDR-DWTJSFPDSA-N,"benzyl N-[(2S)-1-oxo-3,3-diphenyl-1-[(2S)-2-[[...",CHEMBL418050,8.02,CHEMBL2319,ChEMBL,NaN
3,9895762,CS(=O)(=O)C1=CC=CC=C1C2=CC(=C(C=C2)NC(=O)C3=CC...,"InChI=1S/C25H20F4N4O3S/c1-37(35,36)22-8-3-2-7-...",ZLUOAFAJSUPHOG-UHFFFAOYSA-N,1-[3-(aminomethyl)phenyl]-N-[2-fluoro-4-(2-met...,CHEMBL176140,7.21,CHEMBL2319,ChEMBL,NaN
4,134148669,C[C@H]1COC(=O)NC2=CC(=C(C=C2)C3CC3)CN(C(=O)[C@...,InChI=1S/C33H34FN5O3/c1-18-12-21-6-9-25(18)19(...,YBLXUAHRYXEFCL-WWOZWPLTSA-N,"(2R,15R)-2-[(1-amino-4-fluoroisoquinolin-6-yl)...",CHEMBL3934882,7.82,CHEMBL2319,ChEMBL,NaN
...,...,...,...,...,...,...,...,...,...,...
187,155547612,C1=CC=C(C=C1)COC2=C(C=CC(=C2)NCC3=NC=C(N3)C4=C...,InChI=1S/C24H23N5O/c25-24(26)20-12-11-19(13-22...,VCVHKYALGNGEGS-UHFFFAOYSA-N,4-[(5-phenyl-1H-imidazol-2-yl)methylamino]-2-p...,CHEMBL4535831,4.60,CHEMBL2319,ChEMBL,NaN
188,155557932,B1(C2=CC=CC=C2CC(O1)C3=CC(=CC=C3)C(=N)N)O.Cl,InChI=1S/C15H15BN2O2.ClH/c17-15(18)12-6-3-5-11...,DWPWGKLUIPKSHD-UHFFFAOYSA-N,"3-(1-hydroxy-3,4-dihydro-2,1-benzoxaborinin-3-...",CHEMBL4559317,6.30,CHEMBL2319,ChEMBL,NaN
189,155528746,C1=CC(=CC=C1C(=N)N)NCC2=NC=CN2.Cl,InChI=1S/C11H13N5.ClH/c12-11(13)8-1-3-9(4-2-8)...,RAJJVWPVNQNBLO-UHFFFAOYSA-N,4-(1H-imidazol-2-ylmethylamino)benzenecarboxim...,CHEMBL4461888,4.20,CHEMBL2319,ChEMBL,NaN
190,155533183,C1CC1COC2=C(C=CC(=C2)NCC3=NC=C(N3)C4=CC=CC=C4)...,InChI=1S/C21H23N5O.CH2O2/c22-21(23)17-9-8-16(1...,APPAOTHSGRJITR-UHFFFAOYSA-N,2-(cyclopropylmethoxy)-4-[(5-phenyl-1H-imidazo...,CHEMBL4468959,4.30,CHEMBL2319,ChEMBL,NaN
191,155524369,C1=CC(=CC=C1C(=N)N)NCC2=NC3=C(N2)C=C(C=C3)Cl.Cl,InChI=1S/C15H14ClN5.ClH/c16-10-3-6-12-13(7-10)...,QOCRKSICFCSXRW-UHFFFAOYSA-N,4-[(6-chloro-1H-benzimidazol-2-yl)methylamino]...,CHEMBL4456567,5.70,CHEMBL2319,ChEMBL,NaN

In [47]:
state

'completed'

### Run BindingDB only

In [48]:
file_path=os.path.join(data_path, 'BindingDB_Dec2025.csv')
BDB_data=pd.read_csv(file_path,sep=',',low_memory=False,index_col=0)

In [49]:
bdb=BindingDB(database=BDB_data)
[bdb_dat,bdb_state,bdb_raw]=bdb.compounds(protids,pChEMBL_thres=0,merge_stereoisomers=False)

In [50]:
bdb_dat

,CID,SMILES,inchi,inchikey,iupac_name,uniprotid,BindingDB Ligand Name,pchembl_value,notes,datasource
0,44285350,B1(O[C@@H]2CC3CC([C@@]2(O1)C)C3(C)C)C(CCCC(=S)...,InChI=1S/C37H50BN5O6S/c1-36(2)26-21-29(36)37(3...,KAUYBZJFBAONCO-LTNQQUILSA-N,benzyl N-[(2S)-1-[(2S)-2-[[5-hydrazinyl-5-sulf...,P06870,Peptide boronate::CHEMBL2448441,11.309804,Ki (nM),BindingDB
1,139415805,C1=CC=C2C=C(C(=CC2=C1)C(=O)NC3=CC=C(C=C3)CN)O,InChI=1S/C18H16N2O2/c19-11-12-5-7-15(8-6-12)20...,VRZLGSXKZZLNLO-UHFFFAOYSA-N,N-[4-(aminomethyl)phenyl]-3-hydroxynaphthalene...,P06870,CHEMBL4861066,5.619789,Ki (nM),BindingDB
2,139415805,C1=CC=C2C=C(C(=CC2=C1)C(=O)NC3=CC=C(C=C3)CN)O,InChI=1S/C18H16N2O2/c19-11-12-5-7-15(8-6-12)20...,VRZLGSXKZZLNLO-UHFFFAOYSA-N,N-[4-(aminomethyl)phenyl]-3-hydroxynaphthalene...,P06870,CHEMBL4861066,5.292430,IC50 (nM),BindingDB
3,124166067,C1=CN(C(=O)C(=C1)C2=CC(=NN2)NCC3=CC=C(S3)Cl)CC...,InChI=1S/C15H13ClN4O3S/c16-12-4-3-9(24-12)7-17...,HYFHMVXNRDCJBE-UHFFFAOYSA-N,2-[3-[3-[(5-chlorothiophen-2-yl)methylamino]-1...,P06870,"US9687479, 59 2-[3-(5-[(5-chlorothiophen-2-yl)...",4.000000,IC50 (nM),BindingDB
4,137308194,COC1=CC=CC=C1C(=O)N2C(=CC(=N2)C3=CC=CNC3=O)NCC...,InChI=1S/C21H17ClN4O3S/c1-29-17-7-3-2-5-15(17)...,QTLZDCOXZLGEHT-UHFFFAOYSA-N,3-[5-[(5-chlorothiophen-2-yl)methylamino]-1-(2...,P06870,"US9687479, 132 3-(5-[(5-chlorothiophen-2-yl)me...",4.000000,IC50 (nM),BindingDB
...,...,...,...,...,...,...,...,...,...,...
58,24702512,CC1=CC(=C(C=C1)C(=O)NC2=CC=C(C=C2)CN)O,InChI=1S/C15H16N2O2/c1-10-2-7-13(14(18)8-10)15...,GKPOHSSTLWSOGV-UHFFFAOYSA-N,N-[4-(aminomethyl)phenyl]-2-hydroxy-4-methylbe...,P06870,CHEMBL4847066,4.580044,IC50 (nM),BindingDB
59,150924386,CC(C)C1=CC(=C(C=C1)C(=O)NC2=CC=C(C=C2)CN)O,InChI=1S/C17H20N2O2/c1-11(2)13-5-8-15(16(20)9-...,LERYNNIOTWZURB-UHFFFAOYSA-N,N-[4-(aminomethyl)phenyl]-2-hydroxy-4-propan-2...,P06870,CHEMBL4863108,5.075721,IC50 (nM),BindingDB
60,24705575,C1=CC=C2C(=C1)C=CC(=C2O)C(=O)NC3=CC=C(C=C3)CN,InChI=1S/C18H16N2O2/c19-11-12-5-8-14(9-6-12)20...,QANBHYSEYDYUTP-UHFFFAOYSA-N,N-[4-(aminomethyl)phenyl]-1-hydroxynaphthalene...,P06870,CHEMBL4852575,4.671620,IC50 (nM),BindingDB
61,139416079,COC1=CC2=C(C=C1)C(=C(C=C2)C(=O)NC3=CC=C(C=C3)CN)O,InChI=1S/C19H18N2O3/c1-24-15-7-9-16-13(10-15)4...,TUCBVMZLIZJSTJ-UHFFFAOYSA-N,N-[4-(aminomethyl)phenyl]-1-hydroxy-6-methoxyn...,P06870,CHEMBL4862261,4.793174,IC50 (nM),BindingDB
62,164615664,CC1=CC2=C(C=C1)C=CC(=C2O)C(=O)NC3=CC=C(C=C3)CN,InChI=1S/C19H18N2O2/c1-12-2-5-14-6-9-16(18(22)...,QEUQIUWVPKFAFF-UHFFFAOYSA-N,N-[4-(aminomethyl)phenyl]-1-hydroxy-7-methylna...,P06870,CHEMBL4852387,4.306273,IC50 (nM),BindingDB

In [51]:
bdb_state

'completed'

### Run STITCH only

In [54]:
file_path=os.path.join(data_path,'STITCH.csv')
sttch_data=pd.read_csv(file_path,sep=',',low_memory=False,index_col=0)

In [55]:
stitch = Stitch(database=sttch_data)
[stitch_dat, stitch_state, stitch_raw] = stitch.compounds(protids,merge_stereoisomers=False)

In [56]:
stitch_dat

,CID,SMILES,inchi,inchikey,iupac_name,pchembl_value,datasource,notes
0,90666145,CNC(=O)NCCC1CCN(CC1)C(=O)[C@H](CC2=CC(=CC=C2)C...,InChI=1S/C31H36Cl2N6O4S/c1-36-31(41)37-13-10-2...,VBGVWKFAVGGQCH-NDEPHWFRSA-N,1-[2-[1-[(2S)-3-(3-carbamimidoylphenyl)-2-[[3-...,NaN,Stitch,NaN
1,90666144,CNC(=O)NCCC1CCN(CC1)C(=O)[C@H](CC2=CC(=CC=C2)C...,InChI=1S/C33H42N6O6S/c1-36-33(41)37-15-12-22-1...,HJGBKSHYCKEJGU-LJAQVGFWSA-N,1-[2-[1-[(2S)-3-(3-carbamimidoylphenyl)-2-[[3-...,NaN,Stitch,NaN
2,90666143,C1CN(CCC1CCNC(=O)NCC2=CC=CC=C2)C(=O)[C@H](CC3=...,InChI=1S/C34H44N8O5S/c35-16-12-31(43)40-28-10-...,MSPLGPWDOPYNDZ-PMERELPUSA-N,3-amino-N-[3-[[(2S)-1-[4-[2-(benzylcarbamoylam...,NaN,Stitch,NaN
3,90666142,C1CCC(CC1)NC(=O)NCCC2CCN(CC2)C(=O)[C@H](CC3=CC...,InChI=1S/C33H48N8O5S/c34-16-12-30(42)38-27-10-...,ZJAIGKFWWFYSIY-LJAQVGFWSA-N,3-amino-N-[3-[[(2S)-3-(3-carbamimidoylphenyl)-...,NaN,Stitch,NaN
4,90666140,CNC(=O)NCCC1CCN(CC1)C(=O)[C@H](CC2=CC(=CC=C2)C...,InChI=1S/C28H40N8O5S/c1-32-28(39)33-13-9-19-10...,VEYZPZWWGJRHSB-DEOSSOPVSA-N,3-amino-N-[3-[[(2S)-3-(3-carbamimidoylphenyl)-...,NaN,Stitch,NaN
...,...,...,...,...,...,...,...,...
58,6287,CC(C)[C@@H](C(=O)O)N,"InChI=1S/C5H11NO2/c1-3(2)4(6)5(7)8/h3-4H,6H2,1...",KZSNJWFQEVHDMF-BYPYZUCNSA-N,(2S)-2-amino-3-methylbutanoic acid,NaN,Stitch,NaN
59,6140,C1=CC=C(C=C1)C[C@@H](C(=O)O)N,InChI=1S/C9H11NO2/c10-8(9(11)12)6-7-4-2-1-3-5-...,COLNVLDHVKWLRT-QMMMGPOBSA-N,(2S)-2-amino-3-phenylpropanoic acid,NaN,Stitch,NaN
60,5962,C(CCN)C[C@@H](C(=O)O)N,"InChI=1S/C6H14N2O2/c7-4-2-1-3-5(8)6(9)10/h5H,1...",KDXKERNSBIXSRK-YFKPBYRVSA-N,"(2S)-2,6-diaminohexanoic acid",NaN,Stitch,NaN
61,5960,C([C@@H](C(=O)O)N)C(=O)O,"InChI=1S/C4H7NO4/c5-2(4(8)9)1-3(6)7/h2H,1,5H2,...",CKLJMWTZIZZHCS-REOHCLBHSA-N,(2S)-2-aminobutanedioic acid,NaN,Stitch,NaN
62,5950,C[C@@H](C(=O)O)N,"InChI=1S/C3H7NO2/c1-2(4)3(5)6/h2H,4H2,1H3,(H,5...",QNAYBMKLOCPYGJ-REOHCLBHSA-N,(2S)-2-aminopropanoic acid,NaN,Stitch,NaN

In [57]:
stitch_state

'completed'

### Run CTD only

In [58]:
file_path=os.path.join(data_path, 'CTD_Dec2025.csv')
CTD_data=pd.read_csv(file_path,sep=',',low_memory=False,index_col=0)

In [59]:
ctd = CTD(database=CTD_data)
[ctd_dat, ctd_state, ctd_raw] = ctd.compounds(protids,merge_stereoisomers=False)

In [60]:
ctd_dat

,CID,SMILES,inchi,inchikey,iupac_name,datasource,pchembl_value,notes
0,9117,C1=CC2=C3C(=C1)C4=CC=CC5=C4C6=C(C=C5)C=CC(=C36...,InChI=1S/C22H12/c1-3-13-7-9-15-11-12-16-10-8-1...,GYFAGKUZYNFMBN-UHFFFAOYSA-N,"hexacyclo[12.8.0.02,11.03,8.04,21.017,22]docos...",CTD,NaN,NaN
1,1322,CNNC,"InChI=1S/C2H8N2/c1-3-4-2/h3-4H,1-2H3",DIIIISSCIXVANO-UHFFFAOYSA-N,"1,2-dimethylhydrazine",CTD,NaN,NaN
2,9864378,C1C2CC3CC1CC(C2)(C3)C4=C(C=CC(=C4)C5=CC=C(C=C5...,InChI=1S/C25H26O3/c26-23-7-6-21(20-4-1-16(2-5-...,QAWBIEIZDDIEMW-FPYGCLRLSA-N,(E)-3-[4-[3-(1-adamantyl)-4-hydroxyphenyl]phen...,CTD,NaN,NaN
3,1725,C1=CC(=CC=C1C(=N)N)N,"InChI=1S/C7H9N3/c8-6-3-1-5(2-4-6)7(9)10/h1-4H,...",WPANETAWYGDRLL-UHFFFAOYSA-N,4-aminobenzenecarboximidamide,CTD,NaN,NaN
4,7475,C1=CC(=CC=C1N)[N+](=O)[O-],InChI=1S/C6H6N2O2/c7-5-1-3-6(4-2-5)8(9)10/h1-4...,TYMLOMAKGOJONV-UHFFFAOYSA-N,4-nitroaniline,CTD,NaN,NaN
5,6449839,C(CCC=O)C/C=C\C[C@H](/C=C/C=C/C=C\[C@H](CCCC(=...,InChI=1S/C20H30O5/c21-17-10-6-2-1-3-7-12-18(22...,LVLQYGYNBVIONY-PSPARDEHSA-N,"(5S,6Z,8E,10E,12R,14Z)-5,12-dihydroxy-20-oxoic...",CTD,NaN,NaN
6,7290,C(C(CCl)O)O,"InChI=1S/C3H7ClO2/c4-1-3(6)2-5/h3,5-6H,1-2H2",SSZWWUDQMAHNAQ-UHFFFAOYSA-N,"3-chloropropane-1,2-diol",CTD,NaN,NaN
7,5359268,[Al],InChI=1S/Al,XAGFODPZIPBFFR-UHFFFAOYSA-N,aluminum,CTD,NaN,NaN
8,25517,[NH4+].[Cl-],InChI=1S/ClH.H3N/h1H;1H3,NLXLAEXVIDQMFP-UHFFFAOYSA-N,azanium chloride,CTD,NaN,NaN
9,86278622,O[Si](=O)O.O[Si](=O)O.O[Si](=O)O.O[Si](=O)O.O[...,InChI=1S/2Fe.3Mg.2Na.8H2O3Si/c;;;;;;;8*1-4(2)3...,ULEFFCDROVNTRO-UHFFFAOYSA-N,trimagnesium;disodium;octakis(dihydroxy(oxo)si...,CTD,NaN,NaN
10,2336,C1=CC=C2C3=C4C(=CC2=C1)C=CC5=C4C(=CC=C5)C=C3,InChI=1S/C20H12/c1-2-7-17-15(4-1)12-16-9-8-13-...,FMMWHPNWAFZXNH-UHFFFAOYSA-N,benzo[a]pyrene,CTD,NaN,NaN
11,24408,BrBr,InChI=1S/Br2/c1-2,GDTBXPJZTBHREO-UHFFFAOYSA-N,molecular bromine,CTD,NaN,NaN
12,261,CCCC=O,"InChI=1S/C4H8O/c1-2-3-4-5/h4H,2-3H2,1H3",ZTQSAGDEMFDKMZ-UHFFFAOYSA-N,butanal,CTD,NaN,NaN
13,5460341,[Ca],InChI=1S/Ca,OYPRJOBELJOOCE-UHFFFAOYSA-N,calcium,CTD,NaN,NaN
14,2541,CCOC1=NC2=CC=CC(=C2N1CC3=CC=C(C=C3)C4=CC=CC=C4...,InChI=1S/C24H20N6O3/c1-2-33-24-25-20-9-5-8-19(...,HTQMVQVXFRQIKW-UHFFFAOYSA-N,2-ethoxy-3-[[4-[2-(2H-tetrazol-5-yl)phenyl]phe...,CTD,NaN,NaN
15,5943,C(Cl)(Cl)(Cl)Cl,"InChI=1S/CCl4/c2-1(3,4)5",VZGDMQKNWNREIO-UHFFFAOYSA-N,tetrachloromethane,CTD,NaN,NaN
16,2796,CCOC(=O)C(C)(C)OC1=CC=C(C=C1)Cl,"InChI=1S/C12H15ClO3/c1-4-15-11(14)12(2,3)16-10...",KNHUKKLJHYUCFP-UHFFFAOYSA-N,ethyl 2-(4-chlorophenoxy)-2-methylpropanoate,CTD,NaN,NaN
17,5284373,CC[C@H]1C(=O)N(CC(=O)N([C@H](C(=O)N[C@H](C(=O)...,InChI=1S/C62H111N11O12/c1-25-27-28-40(15)52(75...,PMATZTZNYRCHOR-CGLBZJNRSA-N,"(3S,6S,9S,12R,15S,18S,21S,24S,30S,33S)-30-ethy...",CTD,NaN,NaN
18,107901,C1=CC=C(C(=C1)[C@@H]2[C@@](O2)(CN3C=NC=N3)C4=C...,InChI=1S/C17H13ClFN3O/c18-15-4-2-1-3-14(15)16-...,ZMYFCFLJBGAQRS-IAGOWNOFSA-N,"1-[[(2S,3R)-3-(2-chlorophenyl)-2-(4-fluorophen...",CTD,NaN,NaN
19,11,C(CCl)Cl,InChI=1S/C2H4Cl2/c3-1-2-4/h1-2H2,WSLDOOZREJYCGB-UHFFFAOYSA-N,"1,2-dichloroethane",CTD,NaN,NaN
20,5280805,C[C@H]1[C@@H]([C@H]([C@H]([C@@H](O1)OC[C@@H]2[...,InChI=1S/C27H30O16/c1-8-17(32)20(35)22(37)26(4...,IKGXIBQEEMLURG-NVPNHPEKSA-N,"2-(3,4-dihydroxyphenyl)-5,7-dihydroxy-3-[(2S,3...",CTD,NaN,NaN
21,2723872,C1[C@H]([C@H]([C@@H](C(O1)(CO)O)O)O)O,InChI=1S/C6H12O6/c7-2-6(11)5(10)4(9)3(8)1-12-6...,LKDRXBCSQODPBY-VRPWFDPXSA-N,"(3S,4R,5R)-2-(hydroxymethyl)oxane-2,3,4,5-tetrol",CTD,NaN,NaN
22,123591,C12=C3C4=C5C6=C1C7=C8C9=C1C%10=C%11C(=C29)C3=C...,InChI=1S/C60/c1-2-5-6-3(1)8-12-10-4(1)9-11-7(2...,XMWRBQBLMFGWIX-UHFFFAOYSA-N,"(C60-Ih)[5,6]fullerene",CTD,NaN,NaN
23,5280961,C1=CC(=CC=C1C2=COC3=CC(=CC(=C3C2=O)O)O)O,InChI=1S/C15H10O5/c16-9-3-1-8(2-4-9)11-7-20-13...,TZBJGXHYKVUXJN-UHFFFAOYSA-N,"5,7-dihydroxy-3-(4-hydroxyphenyl)chromen-4-one",CTD,NaN,NaN
24,3639,C1NC2=CC(=C(C=C2S(=O)(=O)N1)S(=O)(=O)N)Cl,"InChI=1S/C7H8ClN3O4S2/c8-4-1-5-7(2-6(4)16(9,12...",JZUFKLXOESDKRF-UHFFFAOYSA-N,"6-chloro-1,1-dioxo-3,4-dihydro-2H-1lambda6,2,4...",CTD,NaN,NaN
25,9131,C1=CC=C2C(=C1)C3=C4C2=CC5=CC=CC6=C5C4=C(C=C6)C=C3,InChI=1S/C22H12/c1-2-7-17-16(6-1)18-11-10-14-9...,SXQBHARYMNFBPS-UHFFFAOYSA-N,"hexacyclo[16.3.1.02,7.08,21.011,20.014,19]doco...",CTD,NaN,NaN
26,47576,CC(=O)N1CCN(CC1)C2=CC=C(C=C2)OC[C@@H]3CO[C@@](...,InChI=1S/C26H28Cl2N4O4/c1-19(33)31-10-12-32(13...,XMAYWYJOQHXEEK-ZEQKJWHPSA-N,"1-[4-[4-[[(2S,4R)-2-(2,4-dichlorophenyl)-2-(im...",CTD,NaN,NaN
27,5462224,[Mg],InChI=1S/Mg,FYYHWMGAXLPEAU-UHFFFAOYSA-N,magnesium,CTD,NaN,NaN
28,4156,COS(=O)(=O)C,"InChI=1S/C2H6O3S/c1-5-6(2,3)4/h1-2H3",MBABOKRGFJTBAE-UHFFFAOYSA-N,methyl methanesulfonate,CTD,NaN,NaN
29,20393,CCCCC(CC)COC(=O)C1=CC=CC=C1C(=O)O,InChI=1S/C16H22O4/c1-3-5-8-12(4-2)11-20-16(19)...,DJDSLBVSSOQSLW-UHFFFAOYSA-N,2-(2-ethylhexoxycarbonyl)benzoic acid,CTD,NaN,NaN
30,179931,[O-2].[Ni+2],InChI=1S/Ni.O/q+2;-2,KVAWBJDCAFOHRG-UHFFFAOYSA-N,nickel(2+);oxygen(2-),CTD,NaN,NaN
31,145068,[N]=O,InChI=1S/NO/c1-2,MWUXSHHQAYIFBG-UHFFFAOYSA-N,nitric oxide,CTD,NaN,NaN
32,8063,CCCCC=O,"InChI=1S/C5H10O/c1-2-3-4-5-6/h5H,2-4H2,1H3",HGBOYTHUEUWSSQ-UHFFFAOYSA-N,pentanal,CTD,NaN,NaN
33,5694,CC1=C(C(=CC=C1)NC2=CC(=NC(=N2)SCC(=O)O)Cl)C,InChI=1S/C14H14ClN3O2S/c1-8-4-3-5-10(9(8)2)16-...,SZRPDCCEHVWOJX-UHFFFAOYSA-N,"2-[4-chloro-6-(2,3-dimethylanilino)pyrimidin-2...",CTD,NaN,NaN
34,5462222,[K],InChI=1S/K,ZLMJMSJWJFRBEC-UHFFFAOYSA-N,potassium,CTD,NaN,NaN
35,527,CCC=O,"InChI=1S/C3H6O/c1-2-3-4/h3H,2H2,1H3",NBBJYMSMWIIQGU-UHFFFAOYSA-N,propanal,CTD,NaN,NaN
36,6758,CC(=C)[C@H]1CC2=C(O1)C=CC3=C2O[C@@H]4COC5=CC(=...,InChI=1S/C23H22O6/c1-11(2)16-8-14-15(28-16)6-5...,JUVIOZPCNVVQFO-HBGVWJBISA-N,"(1S,6R,13S)-16,17-dimethoxy-6-prop-1-en-2-yl-2...",CTD,NaN,NaN
37,104858,C(CC(=O)N[C@@H](CSN=O)C(=O)NCC(=O)O)[C@@H](C(=...,InChI=1S/C10H16N4O7S/c11-5(10(19)20)1-2-7(15)1...,HYHSBSXUHZOYLX-WDSKDSINSA-N,(2S)-2-amino-5-[[(2R)-1-(carboxymethylamino)-3...,CTD,NaN,NaN
38,5360545,[Na],InChI=1S/Na,KEAYESYHFKHZAL-UHFFFAOYSA-N,sodium,CTD,NaN,NaN
39,5234,[Na+].[Cl-],InChI=1S/ClH.Na/h1H;/q;+1/p-1,FAPWRFPIFSIZLT-UHFFFAOYSA-M,sodium chloride,CTD,NaN,NaN
40,29327,CN(C(=O)N[C@@H]1[C@H]([C@@H]([C@H](O[C@@H]1O)C...,InChI=1S/C8H15N3O7/c1-11(10-17)8(16)9-4-6(14)5...,ZSJLQEPLLKMAKR-GKHCUFPYSA-N,"1-methyl-1-nitroso-3-[(2S,3R,4R,5S,6R)-2,4,5-t...",CTD,NaN,NaN
41,15625,C1=C2C(=CC(=C1Cl)Cl)OC3=CC(=C(C=C3O2)Cl)Cl,InChI=1S/C12H4Cl4O2/c13-5-1-9-10(2-6(5)14)18-1...,HGUFODBRKLSHSI-UHFFFAOYSA-N,"2,3,7,8-tetrachlorodibenzo-p-dioxin",CTD,NaN,NaN
42,5426,C1CC(=O)NC(=O)C1N2C(=O)C3=CC=CC=C3C2=O,InChI=1S/C13H10N2O4/c16-10-6-5-9(11(17)14-10)1...,UEJJHQNACJXSKW-UHFFFAOYSA-N,"2-(2,6-dioxopiperidin-3-yl)isoindole-1,3-dione",CTD,NaN,NaN
43,26042,O=[Ti]=O,InChI=1S/2O.Ti,GWEVSGVZZGPLCZ-UHFFFAOYSA-N,dioxotitanium,CTD,NaN,NaN
44,444795,CC1=C(C(CCC1)(C)C)/C=C/C(=C/C=C/C(=C/C(=O)O)/C)/C,InChI=1S/C20H28O2/c1-15(8-6-9-16(2)14-19(21)22...,SHGAZHPCJJPHSC-YCNIQYBTSA-N,"(2E,4E,6E,8E)-3,7-dimethyl-9-(2,6,6-trimethylc...",CTD,NaN,NaN
45,6575,C(=C(Cl)Cl)Cl,InChI=1S/C2HCl3/c3-1-2(4)5/h1H,XSTXAVWGXDQKEL-UHFFFAOYSA-N,"1,1,2-trichloroethene",CTD,NaN,NaN
46,39676,CC1(C(=O)N(C(=O)O1)C2=CC(=CC(=C2)Cl)Cl)C=C,InChI=1S/C12H9Cl2NO3/c1-3-12(2)10(16)15(11(17)...,FSCWZHGZWWDELK-UHFFFAOYSA-N,"3-(3,5-dichlorophenyl)-5-ethenyl-5-methyl-1,3-...",CTD,NaN,NaN

In [61]:
ctd_state

'completed'

### Run DTC only

In [62]:
file_path=os.path.join(data_path, 'DTC_Dec2025.csv')
DTC_data=pd.read_csv(file_path,sep=',',low_memory=False,index_col=0)

In [63]:
dtc = DTC(database=DTC_data)
[dtc_dat, dtc_state, dtc_raw] = dtc.compounds(protids,pChEMBL_thres=0,merge_stereoisomers=False)

In [64]:
dtc_dat

,inchi,inchikey,isomeric_smiles,iupac_name,molecular_weight,datasource,pchembl_value
0,InChI=1S/C16H18N2O2/c1-19-14-5-4-10-2-3-11(16(...,None,None,7-methoxy-8-(oxolan-3-yl)naphthalene-2-carboxi...,270.33,DTC,5.481486
1,InChI=1S/C18H15N3O/c19-17(20)14-8-6-13-11-15(9...,None,None,6-carbamimidoyl-N-phenylnaphthalene-2-carboxamide,289.3,DTC,5.602060
2,InChI=1S/C23H24N2O/c1-14(2)26-20-5-3-4-17(12-2...,None,None,6-[2-(3-propan-2-yloxyphenyl)cyclopropyl]napht...,344.4,DTC,5.853252
3,InChI=1S/C27H22N4O3S/c1-18-16-25(31(30-18)23-1...,None,None,5-methyl-2-naphthalen-2-yl-N-[4-(2-sulfamoylph...,482.6,DTC,4.958607
4,InChI=1S/C36H45F3N6O5/c1-20(2)29(45-34(49)50-3...,None,None,1-adamantyl N-[(2R)-1-[[(2S)-1-[[1-[4-(diamino...,698.8,DTC,3.718967
...,...,...,...,...,...,...,...
186,InChI=1S/C29H29N5O3/c1-29(2)17-37-28(36)34-22-...,None,None,"(2S)-2-[(1-aminoisoquinolin-6-yl)amino]-15,15-...",495.6,DTC,7.508638
187,InChI=1S/C28H27N5O3/c1-17-16-36-28(35)33-22-4-...,None,None,(15S)-2-[(1-aminoisoquinolin-6-yl)amino]-15-me...,481.5,DTC,8.397940
188,InChI=1S/C27H25N5O3/c28-25-23-9-8-22(15-20(23)...,None,None,"2-[(1-aminoisoquinolin-6-yl)amino]-13-oxa-4,11...",467.5,DTC,7.455932
189,InChI=1S/C29H29N5O3/c1-29(2)17-37-28(36)34-22-...,None,None,"(2R)-2-[(1-aminoisoquinolin-6-yl)amino]-15,15-...",495.6,DTC,7.602060
190,InChI=1S/C30H31N5O3/c1-30(2)18-38-29(37)34-23-...,None,None,"(2S)-2-[(1-aminoisoquinolin-6-yl)amino]-4,15,1...",509.6,DTC,6.812479

In [65]:
dtc_state

'completed'

### Run OTP only

In [66]:
file_path=os.path.join(data_path, 'OTP_Dec2025.csv')
OTP_data=pd.read_csv(file_path, sep=',',low_memory=False,index_col=0)

In [67]:
otp=OTP(database=OTP_data)
[otp_dat, otp_state, otp_raw] = otp.compounds(protids,merge_stereoisomers=False)

In [68]:
otp_dat

Empty DataFrame
Columns: [inchi, inchikey, isomeric_smiles, iupac_name, datasource, pchembl_value]
Index: []

In [69]:
otp_state

'No interaction data in local OTP'

### Run DrugCentral only

In [70]:
file_path=os.path.join(data_path, 'DrugCentral_Dec2025.csv')
DC_data=pd.read_csv(file_path, sep=',',low_memory=False,index_col=0)

In [71]:
dc = DrugCentral(database=DC_data)
[DC_dat, DC_state, DC_raw] = dc.compounds(input_protein=protids,merge_stereoisomers=False)

In [72]:
DC_dat

Empty DataFrame
Columns: [inchi, inchikey, isomeric_smiles, iupac_name, datasource, pchembl_value]
Index: []

In [73]:
DC_state

'Filter reduced interactions to 0'

### Run DrugBank only

In [74]:
file_path=os.path.join(data_path, 'DB_Dec2025.csv')
DB_data=pd.read_csv(file_path, sep=',',low_memory=False,index_col=0)

In [75]:
db = DB(database=DB_data)
[DB_dat, DB_state, DB_raw] = db.compounds(protids,merge_stereoisomers=False)

In [76]:
DB_dat

,inchi,inchikey,isomeric_smiles,iupac_name,datasource,pchembl_value,CID,SMILES,compound_id,compound_name,hgnc_id,notes
0,InChI=1S/Al,XAGFODPZIPBFFR-UHFFFAOYSA-N,NaN,aluminum,DrugBank,NaN,5359268.0,[Al],DB01370,Aluminium,HGNC:6357,NaN
1,"InChI=1S/C7H8N2/c8-7(9)6-4-2-1-3-5-6/h1-5H,(H3...",PXXJHWLDUBFPOL-UHFFFAOYSA-O,NaN,[amino(phenyl)methylidene]azanium,DrugBank,NaN,444655.0,C1=CC=C(C=C1)C(=[NH2+])N,DB03127,Benzamidine,HGNC:6357,NaN
2,"InChI=1S/C6H7N/c7-6-4-2-1-3-5-6/h1-5H,7H2",PAYRUJLWNCNPSJ-UHFFFAOYSA-N,NaN,aniline,DrugBank,NaN,6115.0,C1=CC=C(C=C1)N,DB06728,Aniline,HGNC:6357,NaN
3,InChI=1S/C19H17N5O2/c20-17(21)14-2-1-13-10-16(...,MQQNFDZXWVTQEH-UHFFFAOYSA-N,NaN,(6-carbamimidoylnaphthalen-2-yl) 4-(diaminomet...,DrugBank,NaN,4413.0,C1=CC(=CC=C1C(=O)OC2=CC3=C(C=C2)C=C(C=C3)C(=N)...,DB12598,Nafamostat,HGNC:6357,NaN
4,"InChI=1S/Al.H3O4P/c;1-5(2,3)4/h;(H3,1,2,3,4)/q...",ILRRQNADMUWWFW-UHFFFAOYSA-K,NaN,aluminum phosphate,DrugBank,NaN,64655.0,[O-]P(=O)([O-])[O-].[Al+3],DB14517,Aluminium phosphate,HGNC:6357,NaN
5,"InChI=1S/3C2H4O2.Al/c3*1-2(3)4;/h3*1H3,(H,3,4)...",WCOATMADISNSBV-UHFFFAOYSA-K,NaN,aluminum triacetate,DrugBank,NaN,8757.0,CC(=O)[O-].CC(=O)[O-].CC(=O)[O-].[Al+3],DB14518,Aluminum acetate,HGNC:6357,NaN

In [77]:
DB_state

'completed'